### ISSUE TITLE
Metadata/Primatives

### ISSUE THREAD

**Issue by swynter-ladbrokes** [BurntSushi/toml#104]
I've found the documentation a little confusing, so some clarification

can I use primatives with just toml.Decode() or does it have to be metadata.Decode()?

toml.PrimitiveDecode is deprecated, so instead of calling module.Setup(somePrimativeConfig) I actually need to call module.Setup(metadata, somePrimativeConfig)?

**Comment by cespare** [comment]
> can I use primatives with just toml.Decode() or does it have to be metadata.Decode()?

You can just use toml.Decode.

> toml.PrimitiveDecode is deprecated, so instead of calling module.Setup(somePrimativeConfig) I actually need to call module.Setup(metadata, somePrimativeConfig)?

I'm not sure what module.Setup is.

The (only) reason to use `(*Metadata).DecodePrimitive` is to update the metadata with the keys that are decoded. That's what the following paragraph (from the `PrimitiveDecode` doc) is saying:

> Meta data for primitive values is included in the meta data returned by the `Decode*` functions with one exception: keys returned by the Undecoded method will only reflect keys that were decoded. Namely, any keys hidden behind a Primitive will be considered undecoded. Executing this method will update the undecoded keys in the meta data. 

If you don't care about the metadata, you can use `toml.Decode` only. 

Hope this helps!
