### ISSUE TITLE
Fully document struct encoding/decoding logic

### ISSUE THREAD

**Issue by cespare** [BurntSushi/toml#121]
The docs should be as comprehensive as encoding/json docs. Some missing things:

- Mention that only exported struct fields can be considered
- Document how struct field tags work
- omitempty

**Comment by Ilyes512** [comment]
This got me as well. I was trying to Decode a TOML file into a struct with only private fields. Would indeed be nice if this is mentioned.

**Comment by Endothelium** [comment]
Same here. Lost 1 hour figuring why decode wasn't working.
