### ISSUE TITLE
Parsing different structures depending on a field

### ISSUE THREAD

**Issue by rasky** [BurntSushi/toml#125]
Hi, I would like to parse a TOML made like this:

```
[connection]
type = "http"

    [connection.config]
    url = "https://foobar.com/api"
    forcessl = True
```

or:

```
[connection]
type = "tcp"

    [connection.config]
    ip = "12.12.12.12"
    port = 1234
```

so basically the `config` table changes its keys depending on `connection.type`. It looks like this library allows me to define a structure like this:

```
type Connection struct {
    Type string
    Config interface{}
}
```
and then the `config` table is read into a `map[string]interface{}`. Instead, I would be able to decode those configuration keys into their own structures, such as:

```
type ConfigHttp struct {
    Url string
    ForceSsl bool
}

type ConfigIp struct {
    Host string
    Port int
}
```

So, I have two questions:

   1. Is it possible to first parse the config file, and later, once the Type has been parsed, further decode the `map[string]interface{}` into the actual structure? I couldn't find an API to do this.
   1. Alternatively, I tried parsing the file two times (which would be acceptable). The first time, the `map[string]interface{}` is generated, but I ignore it. I then instantiate the correct configuration structure and put it into the `config` field, eg: `conn.Config = ConfigHttp{}` and proceed to run a second decoding, but unfortunately it seems to be ignored by the library, because the field's content is discarded and overwritten with a new `map[string]interface{}` instance. BTW this behavior doesn't match what I would expect; for instance, when I use `encoding/json` to decode a JSON into a structure that contains an `interface{}` with a reference to an actual object, the library "sees through" the `interface{}` and decodes into the actual structure.

Would you accept a patch that implements the roadmap presented in option 2? That is, if an `interface{}` field is non-nil and is a struct, decodes into it rather than just overwriting it with the `map[string]interface{}` instance?

**Comment by cespare** [comment]
Use `toml.Primitive` to delay encoding instead of `interface{}`. (This is like `json.RawMessage`.)

``` go
package main

import (
	"fmt"
	"log"

	"github.com/BurntSushi/toml"
)

type ConfigHTTP struct {
	URL      string
	ForceSSL bool
}

type ConfigIP struct {
	Host string
	Port int
}

const input0 = `
[connection]
type = "http"
    [connection.config]
    url = "https://foobar.com/api"
    forcessl = true
`

const input1 = `
[connection]
type = "tcp"
	[connection.config]
        host = "12.12.12.12"
	port = 1234
`

type connection struct {
	Connection struct {
		Type   string
		Config toml.Primitive
	}
}

func parseConfig(s string) (interface{}, error) { // or return a more specific interface
	var conn connection
	md, err := toml.Decode(s, &conn)
	if err != nil {
		return nil, err
	}
	var conf interface{}
	switch conn.Connection.Type {
	case "http":
		conf = new(ConfigHTTP)
	case "tcp":
		conf = new(ConfigIP)
	default:
		return nil, fmt.Errorf("unknown type %q", conn.Connection.Type)
	}
	if err := md.PrimitiveDecode(conn.Connection.Config, conf); err != nil {
		return nil, err
	}
	return conf, nil
}

func main() {
	for _, s := range []string{input0, input1} {
		conf, err := parseConfig(s)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%#v\n", conf)
	}
}
```

```
&main.ConfigHTTP{URL:"https://foobar.com/api", ForceSSL:true}
&main.ConfigIP{Host:"12.12.12.12", Port:1234}
```

**Comment by rasky** [comment]
Thanks, I'm trying this approach now. I found out that, if the config section is not presente, `PrimitiveDecode()` exits with an error: `Type mismatch for main.ConfigHTTP. Expected map but found '<nil>'.`. You can try by changing one of your test inputs like this:

```
const input0 = `
[connection]
type = "http"
`
```

Is this behavior expected?

**Comment by cespare** [comment]
Interesting, that should work. I filed #126.

In the meantime, you can work around this by using a `*Primitive` and explicitly checking the nil case yourself:

http://play.golang.org/p/fKiiL7a-uc

**Comment by cespare** [comment]
Hey @rasky, I also fixed the empty Primitive case so now my original code works if you don't have any config section.

**Comment by rasky** [comment]
Thanks! BTW I suggest you add this or a similar example of delayed encoding to the README
