### ISSUE TITLE
Encoding for embedded structs

### ISSUE THREAD

**Issue by yoava333** [BurntSushi/toml#127]
I'm using the library for decoding toml files, but recently I tried to use it to write out the config and I think I encountered a bug.

```golang
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/BurntSushi/toml"
)

type ServerConf struct {
	Port int `toml:"port"`
}

type Config struct {
	ServerConf `toml:"server"`
}

func main() {
	var tomlStr = `
        [server]
        port = 5        
    `

	conf := &Config{}
	if _, err := toml.Decode(tomlStr, &conf); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("decoded - %#v\n", conf)

	buf := new(bytes.Buffer)
	if err := toml.NewEncoder(buf).Encode(conf); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("encoded - %v\n", buf.String())

}
```

The output is:
```
decoded - &main.Config{ServerConf:main.ServerConf{Port:5}}
encoded - port = 5
```

I was expecting 
```
decoded - &main.Config{ServerConf:main.ServerConf{Port:5}}
encoded - [server]
port = 5
```

This behavior seems inconsistent, It succeeds in parsing but fails on encoding.

**Comment by e-dard** [comment]
I'm seeing this issue too. Would be interested to know thoughts on whether this will be fixed or not?

**Comment by cespare** [comment]
To be precise, I think what we want to do here is copy the following encoding/json behavior:

>  An anonymous struct field with a name given in its JSON tag is treated as having that name, rather than being anonymous.

**Comment by cespare** [comment]
I opened PR #128 for this change.
