### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by PaluMacil** [BurntSushi/toml#138]
Without a license, I feel unsafe using the library.

**Comment by BurntSushi** [comment]
There is a license. See [`COPYING`](https://github.com/BurntSushi/toml/blob/master/COPYING).

**Comment by PaluMacil** [comment]
I see. I am used to looking for "license.md", but Googling "copying" indicates that it's very common and probably moreso for this type of license. Thanks for the help and the excellent license!

**Comment by jayunit100** [comment]
hmm ok , I guess COPYING is the same as LICENSE.
