### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by armon** [BurntSushi/toml#148]
Could you please provide a license file or note in the README for the project? Thanks!

**Comment by cespare** [comment]
See COPYING

**Comment by armon** [comment]
@cespare appreciate it! Might be easier to use MIT, it'll cause less legal hassle for other folks I'm sure.

**Comment by cespare** [comment]
Up to @BurntSushi.

**Comment by BurntSushi** [comment]
It's not really up to me. There are 27 contributors to this project. Some subset of them would probably have to agree with it.

(These days I put all new projects under both the MIT and UNLICENSE.)
