### ISSUE TITLE
toml file doesn't map correctly

### ISSUE THREAD

**Issue by intel352** [BurntSushi/toml#149]
@BurntSushi I built my toml file and structs from the example provided with the toml library, yet when using a `map[string]interface{}` mapping, the mapping fails.

toml file:
```
[scene7]
url = "http://brand.scene7.com/is/image"
paths = ["/brand/usgoods_", "/brand/goods_"]

[formats]

  [formats.main]
  pattern = "{colorcode}_{productid}"

  [formats.swatch]
  pattern = "{colorcode}_{productid}_chip"

  [formats.alt]
  pattern = "{productid}_sub{index}"
```

structs:
```
type tomlConfig struct {
    Scene7 scene7
}

type scene7 struct {
    Url string
    Paths []string
    Formats map[string]format
}

type format struct {
    Pattern string
}
```

execution logic:
```
    var config tomlConfig
    configFile := "config.toml"

    if _, err := toml.DecodeFile(configFile, &config); err != nil {
        fmt.Println(err)
        return
    }
```

Structure of `config` when I dump it out:
```
(main.tomlConfig) {
 Scene7: (main.scene7) {
  Url: (string) (len=32) "http://brand.scene7.com/is/image",
  Paths: ([]string) (len=2 cap=2) {
   (string) (len=15) "/brand/usgoods_",
   (string) (len=13) "/brand/goods_"
  },
  Formats: (map[string]main.format) <nil>
 }
}
```

**Comment by cespare** [comment]
`formats` isn't nested under `scene7` in your TOML, but it is in the Go struct you're unmarshaling into.

Two ways you could fix this:

1. Move `Formats map[string]format` into `tomlConfig`: https://play.golang.org/p/DSPsggEHYY
2. Nest `formats` under `scene7` in the TOML: https://play.golang.org/p/I5uZ8fAuqi

**Comment by intel352** [comment]
Ahhh... So is this an intentional limitation, to not support deeper nests?

**Comment by intel352** [comment]
Ugh, nevermind, I see what I did. I already had Formats in the toml definition as existing at the same level as Scene7. Apologies for the invalid ticket, thanks for the correction. Case of not seeing the forest for the trees.
