### ISSUE TITLE
Lower case in toml, upper case in struct. Bug?

### ISSUE THREAD

**Issue by flawiddsouza** [BurntSushi/toml#151]
This is my toml file:
```
port = 8080
enableAuth = true
username = "user"
password = "pass"
```
This is the struct I'm using:
```
type Configuration struct {
    Port int
    EnableAuth bool
    Username string
    Password string
}
```
Why doesn't this struct work?
```
type Configuration struct {
    port int
    enableAuth bool
    username string
    password string
}
```
I'm new to Go, so maybe I might be missing something. Is this intentional?

**Comment by cespare** [comment]
You can only unmarshal into exported struct fields (the library can't touch your private fields). This is the same as, for example, encoding/json, but unfortunately it's not well-documented in this library.

I generalized the existing bug #121 a bit to mention these missing docs.

**Comment by flawiddsouza** [comment]
Thanks!

**Comment by flawiddsouza** [comment]
Thanks!

**Comment by flawiddsouza** [comment]
Thank you!
