### ISSUE TITLE
Accept []byte for Decode

### ISSUE THREAD

**Issue by ahmetalpbalkan** [BurntSushi/toml#153]
When we read things from files, they almost always come to us as `[]byte`. There's absolutely no reason to convert them to `string` type (unless you want to allocate extra memory for no reason and spend time copying []byte into string).

`toml.Decode` accepts `string` as input. Many other decoders (json, xml, yaml) work with `[]byte` out of the box. `toml` package does not accept `[]byte` anywhere. Therefore users of `toml` have to convert their []byte(s) to string(s) which would result in:

- allocate extra copy of the slice just because you're converting to string
- time spent copying the slice contents to string

I think this package can support `[]byte` just fine, too. Perhaps make a new `DecodeBytes` method which is also used by `Decode`? This way it will be backwards-compatible, too.

**Comment by BurntSushi** [comment]
Why can't you use DecodeReader instead?

TOML isn't json, yaml or xml. I would be surprised to hear of a a use case where converting TOML data to a string was actually unacceptable. Is there a a benchmark you have in mind?

**Comment by BurntSushi** [comment]
To be clear, I'm not in principle against the addition of a DecodeBytes method. My main point here is this: if we added such a method and implemented it as DecodeString(string(bytes)), would you notice? 

If so, I suspect this issue will go deeper than simply exporting a method.

**Comment by ahmetalpbalkan** [comment]
@BurntSushi it's fair that TOML is not used to encode megabytes of data probably. But I don’t think that is a good excuse to provide a better solution.

If you had converted it to string internally, I would not notice it, but someone who is using TOML to store giant data sets would notice at some point.

**Comment by BurntSushi** [comment]
But "better" isn't clear in this context. "Better" should be motivated by use cases and measurements. If you're storing huge data sets in TOML, then that's likely an abuse. TOML isn't an arbitrary serialization format. It is built to be a human friendly configuration format. The scales are completely different. I dare say that even in the case of large data, a simple copy of the data would be the least of your worries. (Take a peek at parse.go and you will understand.)

I think my original point stands. If you can't tell a naive implementation of DecodeBytes from a proper one, then it probably isn't worth adding. Performance was really not a consideration when building this package. I bet it would be rather difficult to notice the overhead of the extra copy.

**Comment by BurntSushi** [comment]
If new evidence comes to light, feel free to reopen.

**Comment by ahmetalpbalkan** [comment]
Understood. Thank you.
