### ISSUE TITLE
Non-string map-keys

### ISSUE THREAD

**Issue by FDePourcq** [BurntSushi/toml#154]
In decode.go, unifyMap, the key of a map is set with:
```
rvkey.SetString(k)
```
( https://github.com/BurntSushi/toml/blob/master/decode.go#L301 )

If instead the code would be like  
```
		switch rvkey.Kind() {
		default:
			panic(fmt.Sprintf("unsupported type for mapkeys: %v\n", rvkey.Kind()))
		case reflect.String:
			rvkey.SetString(k)
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			if wt, err := strconv.ParseInt(k, 10, 64); err == nil {
				rvkey.SetInt(wt)
			} else {
				panic(fmt.Sprintf("Could not parse as int: %s\n", k))
			}
		case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			if wt, err := strconv.ParseUint(k, 10, 64); err == nil {
				rvkey.SetUint(wt)
			} else {
				panic(fmt.Sprintf("Could not parse as uint: %s\n", k))
			}
		}
```
then it would become possible to read toml-config like 
```
[MyMap]
1 =  ["foo","bar"]
2 =  ["foo","bar"]
```
to a golang 
```
MyMap     *map[int][]string
```

**Comment by leighmcculloch** [comment]
While the specification isn't explicit, I believe it is implied that keys are always strings. Otherwise bare keys would appear inconsistent in situations like the below.

```toml
[MyMap]
1 =  ["foo","bar"]
1b =  ["foo","bar"]
2 =  ["foo","bar"]
```

```go
map[interface{}][]string {
  1: ...,
  "1b": ...,
  2: ...,
}
```
The inconsistency in key type would probably result in code using the map incorrectly performing lookups, since the developer would need to remember to use integers for digit-only keys.

**Comment by cespare** [comment]
Keys are strings.

**Comment by neclepsio** [comment]
I understand keys are strings in TOML. 

Still, as special case, when encoding to and decoding from `map[someType]interface{}` automatic conversion could be applied. `someType` could be, for example, numbers and TextMarshalers/TextUnmarshalers.

I don't think this would break the spec.

**Comment by leighmcculloch** [comment]
Re-reading, it does make sense to me too now. You're right, it doesn't change the specification, it just expands the ability for this package to not only unwrap into structs, but maps of different types of keys beyond `string`. Would the error behavior that's introduced for when it's not an `int` be any different to if it tried to decode a field into an int struct value? Maybe this should be expanded beyond keys being just an strings or ints, but to any value?

**Comment by FDePourcq** [comment]
The reason I like the additional types is that it allows me to immediately marshall/demarshall into the internal main datastructure of the application (whose format should be the result of the applications logic and not the philosophy the configuration-tool).

Anyway, I started this issue with code for decoding, while there is also code needed for encoding.
And that has a bit of impact: the order of the map keys is influenced by the type.

Here is a modified version of eMap in decode.go, it tackles a few more non-string datatypes but i did not do any sorting them them:
```
func (enc *Encoder) eMap(key Key, rv reflect.Value) {
	rt := rv.Type()
	switch rt.Key().Kind() {
	default:
		panic(fmt.Sprintf("unsupported type for mapkeys: %v\n", rt.Key().Kind()))
	case reflect.String:
		var mapKeysDirect, mapKeysSub []string
		for _, mapKey := range rv.MapKeys() {
			k := mapKey.String()
			if typeIsHash(tomlTypeOfGo(rv.MapIndex(mapKey))) {
				mapKeysSub = append(mapKeysSub, k)
			} else {
				mapKeysDirect = append(mapKeysDirect, k)
			}
		}

		var writeMapKeys = func(mapKeys []string) {
			sort.Strings(mapKeys)
			for _, mapKey := range mapKeys {
				mrv := rv.MapIndex(reflect.ValueOf(mapKey))
				if isNil(mrv) {
					// Don't write anything for nil fields.
					continue
				}
				enc.encode(key.add(mapKey), mrv)
			}
		}
		writeMapKeys(mapKeysDirect)
		writeMapKeys(mapKeysSub)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		for _, mapKey := range rv.MapKeys() {
			mrv := rv.MapIndex(mapKey)
			if isNil(mrv) {
				// Don't write anything for nil fields.
				continue
			}
			enc.encode(key.add(strconv.FormatInt(int64(mapKey.Int()), 10)), mrv)
		}
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		for _, mapKey := range rv.MapKeys() {
			mrv := rv.MapIndex(mapKey)
			if isNil(mrv) {
				// Don't write anything for nil fields.
				continue
			}
			enc.encode(key.add(strconv.FormatUint(uint64(mapKey.Uint()), 10)), mrv)
		}
	}
}
```
