### ISSUE TITLE
Allow table name to be specified in a tag

### ISSUE THREAD

**Issue by usedbytes** [BurntSushi/toml#161]
I'd like to specify a table name in my `toml` tag:

```
type Table struct {
	Key string
}

type TomlTest struct {
	Table1 Table
	Key2   string `toml:"table2.key"`
}
```

So that given the following input:

```
[table1]
key="Table 1 key"

[table2]
key="Table 2 key"
```

I get:
```
TomlTest{
	Table: {
		Key: "Table 1 key",
	},
	Key2: "Table 2 key",
}
```

But I haven't found a way to make it work. Perhaps my syntax is wrong? Or it's just not supported?

---

Full test code:
```
package main

import (
	"encoding/json"
	"fmt"

	"github.com/BurntSushi/toml"
)

type Table struct {
	Key string
}

type TomlTest struct {
	Table1 Table
	Key2   string `toml:"table2.key"`
}

var tomlBlob = `
[table1]
key="Table 1 key"

[table2]
key="Table 2 key"
`

func main() {
	var t TomlTest

	_, err := toml.Decode(tomlBlob, &t)
	if err != nil {
	    panic(err)
	}

	b, _ := json.MarshalIndent(&t, "", "\t")

	fmt.Println(string(b))
}
```

Output:
```
{
        "Table1": {
                "Key": "Table 1 key"
        },
        "Key2": ""
}
```

Expected output:
```
{
        "Table1": {
                "Key": "Table 1 key"
        },
        "Key2": "Table 2 key"
}
```

**Comment by cespare** [comment]
Thanks for the very clear question with runnable code :)

Destructuring nesting using tags like that isn't supported. You'll need to decode into objects that match the TOML structure and than transform it into a different nesting in a second step. (It's pretty similar to how encoding/json decoding works.)

**Comment by usedbytes** [comment]
OK fair enough, I'll use that approach. Thanks!
