### ISSUE TITLE
Decoder: cannot parse inline tables as array elements

### ISSUE THREAD

**Issue by bluebob** [BurntSushi/toml#163]
Trying the following from the [toml-lang](https://github.com/toml-lang/toml#user-content-inline-table) page:
```
points = [ { x = 1, y = 2, z = 3 },
           { x = 7, y = 8, z = 9 },
           { x = 2, y = 4, z = 8 } ]
```

tomlv replies with:

```~/Go/bin/tomlv test.toml
Error in 'test.toml': Near line 1 (last key parsed 'points'): Expected value but found '{' instead.
```

Reading the docs here, it looks like this should be supported. Am I using something in the TOML spec that hasn't been implemented yet?

**Comment by cespare** [comment]
Nope, this is just a bug. Thanks.

**Comment by cespare** [comment]
Just got around to looking into this and it seems to work fine. I added a test case for it in d3bd83c040073fa87fb20a8682b027849074afa8.

I'm pretty sure you're using an older version of the code. Have you updated your copy of the library recently? Inline table support only landed in master a couple of weeks ago.
