### ISSUE TITLE
Near line 0 (last key parsed ''): Bare keys cannot contain '.'.

### ISSUE THREAD

**Issue by ppallal** [BurntSushi/toml#164]
[dev]
    	host = "0.0.0.0"
    	port = 8080
    	ssl = false
    
    [prod]
    	host = "0.0.0.0"
    	port = 8080
    	ssl = true
    	cert_file = "c:/Users/Prafulla Pallal/.ssh/server.crt"
    	key_file = "c:/Users/Prafulla Pallal/.ssh/server.key"

This is my toml file. The python toml library parses this comfortably. However, when I try to read this file in go I face this error.

     Near line 0 (last key parsed ''): Bare keys cannot contain '.'.

I have tried all possible UTF-8, 16, 32, (BE, LE, Plain), ISO encodings. But this problem seems to remain.

**Comment by BurntSushi** [comment]
Could you please provide a small Go program that reproduces your issue? For example, this program works:

```go
package main

import (
	"fmt"
	"log"

	"github.com/BurntSushi/toml"
)

func main() {
	var s = `
[dev]
	host = "0.0.0.0"
	port = 8080
	ssl = false

[prod]
	host = "0.0.0.0"
	port = 8080
	ssl = true
	cert_file = "c:/Users/Prafulla Pallal/.ssh/server.crt"
	key_file = "c:/Users/Prafulla Pallal/.ssh/server.key"
`
	var config map[string]interface{}
	md, err := toml.Decode(s, &config)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(md.Keys())
}
```

without output:

```
$ go run main.go 
[dev dev.host dev.port dev.ssl prod prod.host prod.port prod.ssl prod.cert_file prod.key_file]
```

**Comment by nebbers1111** [comment]
Make sure you are using the right decode function (using Decode on a file will give you this error, need to use DecodeFile).

**Comment by cespare** [comment]
Closing for now; please reopen if you have a repro.

**Comment by ernestoaparicio** [comment]
I received the same error when i had an empty space at the end of config.toml, removed and message went away.

**Comment by nebloc** [comment]
@ernestoaparicio could you give an example? 

I cannot replicate on latest version. Was the trailing space a Carriage Return + Line Feed? or just a space character?

**Comment by ernestoaparicio** [comment]
@nebloc latest, DecodeFile, with a carriage return, but now I can't duplicate it, lol.

**Comment by starlilyth** [comment]
> Make sure you are using the right decode function (using Decode on a file will give you this error, need to use DecodeFile).

This page has 'Decode' not 'DecodeFile' in the example: https://github.com/BurntSushi/toml
