### ISSUE TITLE
is there any plans to add sub-configuration?

### ISSUE THREAD

**Issue by kekek** [BurntSushi/toml#167]
Whether there are plans to add sub-configuration, such as nginx or supervisor configuration which have a directive “include”, that including sub-files or folders

**Comment by cespare** [comment]
We only want to support things that are in the TOML spec, so we're not going to add new syntax or assign special semantics to any existing syntax.

You can easily implement this yourself, though, by putting an include in a special key or something.

``` toml
include = ["subconfig1.toml", "subconfig2.toml"]
```

You'd parse the toml file and then find/parse the included files.
