### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by AlekSi** [BurntSushi/toml#168]
There are [a bunch of changes in master](https://github.com/BurntSushi/toml/compare/v0.2.0...master).

**Comment by cespare** [comment]
I tagged v0.3.0, but I make zero promises about the semantic meaning of this tag.

**Comment by AlekSi** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

And I'm fine with that. Thank you.
