### ISSUE TITLE
Valid UTF-8 characters not accepted in table names

### ISSUE THREAD

**Issue by cuboci** [BurntSushi/toml#175]
If I use German umlauts in table names, parsing fails with the following error:

`Near line 1 (last key parsed ''): expected '.' or ']' to end table name, but got 'ü' instead`

This is the TOML data:

```
[ü]
        name = "foo"
        value = "bar"
```

parsed into this struct:

```
type Config struct {
        Map map[string]string `toml:"ü"`
}
```

whereas this is parsed perfectly (assuming the struct tag is changed accordingly):

```
[u]
        name = "foo"
        value = "bar"
```

The TOML spec doesn't say anything about table names or keys needing to be US ASCII-clean, only that the file needs to be valid UTF-8. So I assume using valid UTF-8 characters like German umlauts should work. Or am I reading the spec wrong?

Cheers,
  Chris

**Comment by BurntSushi** [comment]
From [the spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md):

> Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). Quoted keys follow the exact same rules as basic strings and allow you to use a much broader set of key names. Best practice is to use bare keys except when absolutely necessary.

Specifically, see the [section on tables](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#table).

**Comment by cuboci** [comment]
Ah, thanks for the info. I completely missed that. (It's hard to see why keys have to be quoted when they don't contain white space or equal signs but that's a different matter.)

**Comment by BurntSushi** [comment]
@cuboci It wasn't always that way. The current scheme is intentionally conservative. It might be loosened some day. There was lengthy discussion about it a while back, but I don't have time to look for it right now.
