### ISSUE TITLE
Support BinaryUnmarshaler and BinaryMarshaler Interfaces

### ISSUE THREAD

**Issue by 0xcaff** [BurntSushi/toml#180]
Is there a reason why these interfaces aren't automatically marshaled/unmarshaled into/out of? This would be useful for using this library with [`*url.URL`](https://godoc.org/net/url#URL.UnmarshalBinary)s.

**Comment by nikkolasg** [comment]
+1 for interfacing with default Golang interfaces.

**Comment by cespare** [comment]
TOML does use the default go textual marshaling interface: TextMarshaler/TextUnmarshaler.

It is not a binary format so it doesn't make sense that it would use BinaryMarshaler/BinaryUnmarshaler interfaces.

It's an unfortunate accident (needed to maintain backwards compatibility) that url.URL doesn't implement TextMarshaler/TextUnmarshaler; see the comment:

    // Would like to implement MarshalText/UnmarshalText but that will change the JSON representation of URLs.

I'd recommend just putting URLs as strings in your structure to be marshaled.
