### ISSUE TITLE
Support map keys that implement TextMarshaler and TextUnmarshaler

### ISSUE THREAD

**Issue by expectation1009** [BurntSushi/toml#181]
```
type Config struct {
	FileName   string
	FileNameCn string
	Cols       map[int]Column
}
```

config like top, when decode will have a error "work faild reflect: call of reflect.Value.SetString on int Value"
if change Cols define to "map[string]Column" it works

**Comment by cespare** [comment]
I don't think I would expect this to work, since TOML doesn't have a way of expressing int keys. The error message is not great, though.

**Comment by shousper** [comment]
@cespare I have a similar issue with a `type Blah int32` from a protobuf enum. I implemented `TextMarshaler` and `TextUnmarshaler` but am still unable to use these as a key for a `map`.

Could this possibly be supported? The configuration would only support the string values, obviously, per the TOML spec.

**Comment by arp242** [comment]
Only `map[string]...` is supported right now, as TOML only supports strings as map keys. I clarified the error message on that in a PR earlier today.

Supporting map keys which support `TextUnmarshaler` and `TextMarshaler` would be an option worth investigating; I can't think of any downsides off-hand, but I'll have to look in more detail later. I'll rename the issue to this.

**Comment by arp242** [comment]
I'm closing this for now as it's not super-clear to me what the practical real-world use case for this is, it's some amount of work to implement, and it doesn't seem to come up that often. If you still want this, then please let me know the use case, so we can see what the best solution is (which may be using TextMarshaler or something else).
