### ISSUE TITLE
switch to MIT license

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/toml#183]
The WTFPL causes people to not want to use this library. Historically, I've been against changing the license mostly because it's just a pain to do so. Ideally, we'd like to get a sign off from all people that have made non-trivial contributions. (And if we can't, we either need to stop the re-licensing process or remove/rewrite those contributions. I'm not particularly inclined to the do latter, but if we can do the former, than we should.)

So, this issue is going to track the relicensing progress. I'll start by listing some of the major contributors, where I interpreted "major" as "100 lines of code or more."

* [x] @BurntSushi
* [x] @cespare 
* [x] @sqs
* [x] @rjeczalik
* [x] @ttacon
* [x] @bbuck
* [x] @halostatue
* [x] @sethwklein

**Comment by BurntSushi** [comment]
Once everyone has signed off, we will switch to the MIT.

**Comment by rjeczalik** [comment]
MIT 👍

**Comment by sqs** [comment]
Sounds good to me. I consent to the relicensing.

**Comment by halostatue** [comment]
👍 I affirm relicensing of my contribution.

**Comment by bbuck** [comment]
I will consent to relicensing as well.

**Comment by sethwklein** [comment]
MIT is fine with me.

**Comment by cespare** [comment]
I'm fine with MIT.

**Comment by ttacon** [comment]
Sounds good to me!

**Comment by BurntSushi** [comment]
Thanks everyone!

... That was much easier than I thought.

**Comment by thaJeztah** [comment]
@BurntSushi are there plans to tag a new release, now that the license changed?
