### ISSUE TITLE
Allow duplicate keys

### ISSUE THREAD

**Issue by bdcribbs** [BurntSushi/toml#186]
We're writing a app where we have multiple toml configuration files in a few locations on disk. We want the ultimate config in our app to be the combination of the two, and on our side we have a priority of the file locations defined to say who should overwrite who.

Currently your parser works great for us, except we have to comment out [the panic](https://github.com/BurntSushi/toml/blob/master/parse.go#L450) when a key has been duplicated. We understand in the usual case a panic is the right way to go, but we would love if the package supported duplicate keys as an option.

**Comment by BurntSushi** [comment]
@bdcribbs The [TOML spec](https://github.com/toml-lang/toml) says this:

> You cannot define any key or table more than once. Doing so is invalid.

I'm not particularly inclined to add options to partially disable parts of the spec.

**Comment by cespare** [comment]
Yeah, seems best to stick with the spec as written.
