### ISSUE TITLE
How to Decode with default values in []struct?

### ISSUE THREAD

**Issue by zerolyd** [BurntSushi/toml#187]
eg:
```
type Server struct {
    Url     string
    Port    int
}

type Host struct {
    Servers []Server
}

var blob = `
[Host]
[[Servers]]
Url = "http://google.com"

[[Servers]]
Url = "http://github.com"
`
``` 

How to  Decode with all Servers Port = 80?

**Comment by cespare** [comment]
Unfortunately, because of the array, there's no good way to do this (because of #169 even meta.IsDefined doesn't help). So you're left with something like https://play.golang.org/p/DJ76rVVE5a for now. Sorry!
