### ISSUE TITLE
Go Program in ARM arch cannot read TOML file

### ISSUE THREAD

**Issue by awmpietro** [BurntSushi/toml#190]
I'm building a Go program from a Mac to run in a Raspberry Pi 3, which is ARM architecture:
`env GOOS=linux GOARCH=arm go install github.com/awmpietro/MY_PROGRAM`
But when i try to run my program from the Raspberry:
`open config.toml: no such file or directory`

My Hierarchy:
```
config
    config.go
vendor
   ...
config.toml
main.go
```

The config/config.go tries to open the TOML file:
```
func (c *Config) Read() {
	if _, err := toml.DecodeFile("config.toml", &c); err != nil {
		log.Fatal(err)
        }
}
```
When i build for MacOS it works fine but in the Raspbian it can't open TOML file. Any Help?

**Comment by BurntSushi** [comment]
I don't see how this is a problem with this library. The error you're seeing is just passed up from an `os.Open` call. I'd recommend debugging it further on your end.
