### ISSUE TITLE
support tuples inside a list

### ISSUE THREAD

**Issue by abdoo** [BurntSushi/toml#196]
Dears,

there is a support for below format

"HttpHeaders": [
    {
      "Key": "123",
      "Value": "xxxx01"
    },
    {
      "Key": "456",
      "Value": "yyyy01"
    }
  ]

Thanks

**Comment by BurntSushi** [comment]
@abdoo I do not understand this issue. Please clarify what it is you want, and more importantly, describe the problem you're trying to solve.

**Comment by abdoo** [comment]
sorry I was coding at the moment :-).
What I sent earlier is the JSON format which server accepts. My configuration is like that

HttpMethod = "POST"
HttpEndpoint = "http://10.10.30.31:8080/api/send"
HttpUsername = "xxxx"
HttpPassword = "xxxx"

And I would like to add headers and I was wondering if toml can parse the below

HttpHeaders = [
    {Key = "123",
     Value = "xxxx01"
    },
    {Key = "456",
     Value = "yyyy01"
    }
]


Thanks,

**Comment by BurntSushi** [comment]
[No](https://github.com/toml-lang/toml#inline-table):

> Inline tables are intended to appear on a single line. No newlines are allowed between the curly braces unless they are valid within a value.

**Comment by abdoo** [comment]
Thanks a lot!
