### ISSUE TITLE
Documentation on whether enums are supported

### ISSUE THREAD

**Issue by tcurdt** [BurntSushi/toml#203]
I cannot find any documentation on whether enums are supported or not. Example:

```
    //go:generate stringer -type=foo
    type foo int
    const (
      A foo = iota
      B
    )

    type Config struct {
      Foo foo
    }
```

**Comment by cespare** [comment]
Yes, this library implements marshaling/unmarshaling between toml integers and Go ints.

**Comment by tcurdt** [comment]
Thanks for answering - but I still don't see that documented anywhere.
It would be great to have this be part of the example.

**Comment by BurntSushi** [comment]
@tcurdt It is [documented](https://godoc.org/github.com/BurntSushi/toml#Decode):

> All other TOML types (float, string, int, bool and array) correspond to the obvious Go types.

The example for that method shows deserializing into `int`.

**Comment by tcurdt** [comment]
Sorry, missed that. Thanks for pointing that out.
That said - while technically it might be the same, I'd still suggest to include an enum style example.
