### ISSUE TITLE
Encode() can panic

### ISSUE THREAD

**Issue by the4thamigo-uk** [BurntSushi/toml#204]
Hi, there are a few places where this function causes a panic in the calling code rather than returning an error object. 

e.g.
```
		panic(e("unsupported type for key '%s': %s", key, k))
```

**Comment by BurntSushi** [comment]
Can you please provide an example program that results in the caller
observing the panic?

**Comment by the4thamigo-uk** [comment]
One example :+1: 
```
func TestPanic(t *testing.T) {
	buf := bytes.Buffer{}
	enc := NewEncoder(&buf)
	data := make(chan int)
	_ = enc.Encode(data)
}
```
