### ISSUE TITLE
Variables with underscore

### ISSUE THREAD

**Issue by fnzv** [BurntSushi/toml#209]
Hello,
I noticed that when reading from a config file with underscore between some variables those are ignored.
For example:
test = 0
test_b = 1
test_c = 1

test_b and test_c are ignored/null value

Is it because of something i'm missing from documentation or it's a issue of the toml parser?

**Comment by BurntSushi** [comment]
Please provide a minimal example of code that compiles and runs. Please provide the input, actual output and state what the expected output is.

**Comment by fnzv** [comment]
https://gist.github.com/fnzv/fce6fb504f45405f947c4f856e27fc2b
I want to read the correct outputs even if there are underscores on test.conf file and on the Struct definition

**Comment by BurntSushi** [comment]
The fields in your TOML data do not contain an underscore, while the fields in your struct do. Therefore, they do no match. This library works like `encoding/json` in the standard library. You need to use struct tags if you want to use a different name. It's documented with an example here: https://godoc.org/github.com/BurntSushi/toml#hdr-Key_mapping

**Comment by fnzv** [comment]
I fixed and kept the same name with no underscore and still i can see the correct output( values 0, 2,2 ):
# ./test-toml
test 0
testb 0
testc 0
😕 

You can still see the code i run on the gist

**Comment by BurntSushi** [comment]
Your fields in your struct are not exported. Therefore, this library can't see them. You need to export them.

**Comment by fnzv** [comment]
My bad.. sorry for opening this issue
