### ISSUE TITLE
it parsed string to int64 again

### ISSUE THREAD

**Issue by Sherlock-Holo** [BurntSushi/toml#220]
my config file:
```
EBusinessID=1338036
AppKey="""d113aa98-addf-4188-91e7-d3deb5dc64dd"""
```

my code:
```
type Config struct {
    EBusinessID string
    AppKey      string
}
```

when I use `_, err = toml.Decode(buf.String(), &conf)`, it will report `toml: cannot load TOML value of type int64 into a Go string`

**Comment by cespare** [comment]
This is working as intended. TOML integer types map to Go integer types; TOML strings map to Go strings.

Either unmarshal into an integer and convert to a string, or write your TOML like

    EBusinessID = "1338036"
