### ISSUE TITLE
Encode without default values?

### ISSUE THREAD

**Issue by jcjordyn130** [BurntSushi/toml#221]
Would it be possible to save a toml file without the default value for unset (strings are blank, int are 0, etc) values?

**Comment by jcjordyn130** [comment]
As of now I have
`    Title = "title"
    Album = "album"
    Artist = "artist"
    AlbumArtist = ""
    Composer = ""
    Genre = ""
    Year = 0
    Track = 2
    Disc = 0
    AlbumArt = ""
`

And I want

`    Title = "title"
    Album = "album"
    Artist = "artist"
    Track = 2
`

**Comment by BurntSushi** [comment]
You do it the same way you would as with `encoding/json`. Use `omitempty`.

**Comment by jcjordyn130** [comment]
Thanks, Tired me didn't do enough googling lol
