### ISSUE TITLE
Partial Decoding possible?

### ISSUE THREAD

**Issue by MTRNord** [BurntSushi/toml#227]
Hi is it possible to have one file but always only decode parts of it into structs? Means for example got the following toml but not at the same time want to unmarshal both things into structs so basicly file A decodes the song part only and the file b the test part only.

```toml
[[song]]
name = "Thunder Road"
duration = "4m49s"
	
[[test]]
name = "Stairway to Heaven"
duration = "8m03s"
```

I tried to do it like this (just as example code) but it never fills the struct.

```golang
package main

import (
	"github.com/BurntSushi/toml"
	"log"
	"time"
)

func main() {
	blob := `
	  [[song]]
	  name = "Thunder Road"
	  duration = "4m49s"
	
	  [[test]]
	  name = "Stairway to Heaven"
	  duration = "8m03s"
	`
	type songT struct {
		Name     string
		Duration time.Duration
	}
	type testT struct {
		Name     string
		Duration time.Duration
	}
	song := &songT{}
	_, err := toml.Decode(blob, song)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("Song: %+v\n", song)

	test := &testT{}
	_, err = toml.Decode(blob, test)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("test: %+v\n", test)
}

```

**Comment by MTRNord** [comment]
PS: it doesnt error

**Comment by MTRNord** [comment]
Also: the metadata gets filled. But the struct does not.

**Comment by MTRNord** [comment]
To explain a bit more: I am writing a framework with independent coded parts and dont want to have a global defined config but have each independent part have its own section in the config file. So 1 config file but not 1 global definition of it

**Comment by cespare** [comment]
Hi @MTRNord, partial decoding works fine (it's the same as encoding/json), but there are a variety of issues with your code.

1. You trying to unmarshal a TOML array (`[[song]]`) into a struct instead of a slice
2. You're unmarshaling directly into a song; the target of unmarshaling needs to correspond to the top-level document
3. You'll need to define a `duration` type; time.Duration doesn't implement TextUnmarshaler (see the README)

Try this:

```
package main

import (
	"log"
	"time"

	"github.com/BurntSushi/toml"
)

type duration struct {
	time.Duration
}

func (d *duration) UnmarshalText(text []byte) error {
	var err error
	d.Duration, err = time.ParseDuration(string(text))
	return err
}

func main() {
	blob := `
	  [[song]]
	  name = "Thunder Road"
	  duration = "4m49s"

	  [[test]]
	  name = "Stairway to Heaven"
	  duration = "8m03s"
	`
	type songT struct {
		Name     string
		Duration duration
	}
	type testT struct {
		Name     string
		Duration time.Duration
	}
	var songs struct{ Song []songT }
	_, err := toml.Decode(blob, &songs)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("Songs: %+v\n", songs)
}
```

**Comment by MTRNord** [comment]
Ah thanks! that helps me a lot 👍
