### ISSUE TITLE
Support TOML 0.5

### ISSUE THREAD

**Issue by AlekSi** [BurntSushi/toml#228]
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md

**Comment by jokeyrhyme** [comment]
I just wanted to double-check, does this implementation support everything in 0.5.0?

https://github.com/toml-lang/toml/blob/v0.5.0/CHANGELOG.md

Including this item from #295 ?

> Need to look at inline tables; that doesn't work yet:
> a = {b.c.d = 1}

**Comment by arp242** [comment]
Yeah, there's a second commit that added that. I just didn't update the PR description.

It *should* support TOML 1.0 now I think, but there may still be some rough edges and/or things I missed – some tests are still failing. I would recommend waiting until there's a tagged release (which should be a matter of 1-2 weeks, I hope).

**Comment by jokeyrhyme** [comment]
No worries, I was just double-checking after seeing the issue closure

Thanks for all the hard work <3
