### ISSUE TITLE
Release a new version for vendor management tool dep

### ISSUE THREAD

**Issue by wweir** [BurntSushi/toml#232]
[Dep](https://github.com/golang/dep) pick semver versions first, it picks `0.0.3` as the default version.
But `0.0.3` release two years ago, all issues fixed in the last two years are missing.

eg: https://github.com/BurntSushi/toml/commit/8482be601623debfad693ca81106d44d3457c1b3
This fixes almost effect half `dep` and `toml` users in the world.

How about release a fix version?

**Comment by PaluMacil** [comment]
@BurntSushi A new tag would also be nice for the go mod command just added in go 1.11 which needs semver versions.

**Comment by cespare** [comment]
I tagged v0.3.1. (The changes since 0.3.0 were very minor.)
