### ISSUE TITLE
More crashes found via fuzzing

### ISSUE THREAD

**Issue by leonklingele** [BurntSushi/toml#239]
More strings were found that crash `toml.Decode`.

### Steps to reproduce

```sh
$ cd $(mktemp -d)
$ git clone https://github.com/leonklingele/fuzzing-BurntSushi-toml
$ cd fuzzing-BurntSushi-toml
$ # The crashing strings can be found in ./workdir/crashers/
$ # A lot are probably duplicates triggering the same panic – I've not filtered them.
$ # Test all strings against the github.com/BurntSushi/toml library found in GOPATH
$ ./runall.sh
```

Related: #114, #155

**Comment by arp242** [comment]
All of these are now fixed.

I also added a `fuzz_test.go` for the new Go 1.17 fuzzer beta in #289; I haven't run it very long yet, but it makes it easier to run fuzz tests if people want it by just using `go test -fuzz`. I'll let it run for a bit before the next release to see what falls out.
