### ISSUE TITLE
Parsing will be dead-lopped if the toml file only consists of one string

### ISSUE THREAD

**Issue by SdaixuS** [BurntSushi/toml#241]
description
===
if the toml file only consists of one string, e.g. "abc", the parsing process will sink into dead-loop.

a way to fix
===
I`ve read the codes, and found the reason. it`s because the lexKey() function, when it peeks the next char and the char is eof, it does nothing and return. which caused the dead loop. can simply fix it by adding one condition "r==eof" as below.
```
// lexKey consumes the text of a key. Assumes that the first character (which
// is not whitespace) has already been consumed.
func lexKey(lx *lexer) stateFn {
	r := lx.peek()

	// XXX: Possible divergence from spec?
	// "Keys start with the first non-whitespace character and end with the
	// last non-whitespace character before the equals sign."
	// Note here that whitespace is either a tab or a space.
	// But we'll call it quits if we see a new line too.
	if isWhitespace(r) || isNL(r) || r == eof {
		lx.emit(itemText)
		return lexKeyEnd
	}

	// Let's also call it quits if we see an equals sign.
	if r == keySep {
		lx.emit(itemText)
		return lexKeyEnd
	}

	lx.next()
	return lexKey
}
```

**Comment by arp242** [comment]
This seems okay now(?) The error it returns is:

    Near line 0 (last key parsed ''): bare keys cannot contain '\x00'

Not sure which version you're using btw; since there is no `lexKey` and there wasn't one in 2019 either, so I think that even at the time it was reported it was already fixed.

That `\x00` in that error isn't especially great btw, I'll get that fixed.
