### ISSUE TITLE
Encoder doesn't support json.Number

### ISSUE THREAD

**Issue by johanfleury** [BurntSushi/toml#252]
When encoding a map that was previously decoded from JSON using [`UseNumber`](https://golang.org/pkg/encoding/json/#Decoder.UseNumber), the TOML encoder marshals integers and floats to string (see https://github.com/helm/helm/issues/6539 and https://play.golang.org/p/afaXYox7qBP).

For some reason the [YAML encoder](https://github.com/ghodss/yaml) used by Helm is not facing the same issue, but I couldn't find any kind of special treatment for `json.Number`.

I'm not a Go programmer, but I think we could deal with such case with something like that:

```
func convertJSONNumber(n json.Number) (interface{}, error) {
	i, err1 := n.Int64()
	if err1 != nil {
		f, err2 := n.Float64()
		if err2 != nil {
			return 0, errors.New(fmt.Sprintf("Unable to convert %s to neither int64 nor float64", n))
		}
		return f, nil
	}
	return i, nil
}
```

See: https://play.golang.org/p/YiE1vIlNRd6

**Comment by johanfleury** [comment]
I played a bit with `encode.go` and came with this diff (that seems to work):

```diff
diff --git a/encode.go b/encode.go
index d905c21..f7b16e6 100644
--- a/encode.go
+++ b/encode.go
@@ -2,6 +2,7 @@ package toml
 
 import (
        "bufio"
+       "encoding/json"
        "errors"
        "fmt"
        "io"
@@ -114,6 +115,18 @@ func (enc *Encoder) encode(key Key, rv reflect.Value) {
        case time.Time, TextMarshaler:
                enc.keyEqElement(key, rv)
                return
+       case json.Number:
+               n, _ := rv.Interface().(json.Number)
+
+               if v, err := n.Int64(); err == nil {
+                       enc.keyEqElement(key, reflect.ValueOf(v))
+                       return
+               }
+               if v, err := n.Float64(); err == nil {
+                       enc.keyEqElement(key, reflect.ValueOf(v))
+                       return
+               }
+               encPanic(errors.New(fmt.Sprintf("Unable to convert \"%s\" to neither int64 nor float64", n)))
        }
 
        k := rv.Kind()
```

Tell me if that's an acceptable fix and I'll do a proper pull request.

**Comment by arp242** [comment]
`json.Number` is:

```
type Number string

// String returns the literal text of the number.
func (n Number) String() string { return string(n) }

// Float64 returns the number as a float64.
func (n Number) Float64() (float64, error) {
    return strconv.ParseFloat(string(n), 64)
}

// Int64 returns the number as an int64.
func (n Number) Int64() (int64, error) {
    return strconv.ParseInt(string(n), 10, 64)
}
```

I guess the YAML library uses the `Int64()` or `Float64` methods? Or something?

Either way, I'm not sure if having a special case for this is the best solution, but I'd have to look in to this a bit deeper to be sure.

**Comment by arp242** [comment]
I took a closer look at that YAML package, and the reason it works in there is because:

> this package first converts YAML to JSON using go-yaml and then uses json.Marshal and json.Unmarshal to convert to or from the struct.

So it just uses the `encoding/json` code for this.
