### ISSUE TITLE
2 fields in struct are not being read in struct

### ISSUE THREAD

**Issue by harsh-mittal** [BurntSushi/toml#258]
I'm trying to read a toml file into a struct in Golang but 2 fields in it are not being populated.

Failing Scenarios
* replace hyphen with underscore, both in code and file
* remove struct tags

Pass Scenario
* use exact same name for fields, no hyphen or underscore

Is there something I'm missed? Please help.
check here for code to reproduce this bug [Github Repo](https://github.com/harsh-mittal/bad-sushi)

**Comment by arp242** [comment]
The problem in that repo is that there is a space after `toml: ` in the struct tags:

	Host           string `toml: "host"`

should be:

	Host           string `toml:"host"`

`go vet` will catch this error:

```
$ go vet .
# github.com/BurntSushi/toml
./decode_test.go:1621:3: struct field tag `toml: "host"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
./decode_test.go:1622:3: struct field tag `toml: "port"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
./decode_test.go:1623:3: struct field tag `toml: "max-connections"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
./decode_test.go:1624:3: struct field tag `toml: "log-level"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```

It's a bit finicky, but this is the case for all struct tags, and how Go parses them. Nothing this library can do about that.

If I fix that then if works:

	func Test258(t *testing.T) {
		file := `
	host = "127.0.0.1"
	port = 9080
	max-connections = 1
	log-level = "debug"
	`

		type tcpConfig struct {
			Host           string `toml:"host"`
			Port           int    `toml:"port"`
			MaxConnections int    `toml:"max-connections"`
			LogLevel       string `toml:"log-level"`
		}

		var c tcpConfig
		_, err := Decode(file, &c)
		fmt.Println(err)
		fmt.Printf("%#v\n", c)
	}

Outputs:

    <nil>
    toml.tcpConfig{Host:"127.0.0.1", Port:9080, MaxConnections:1, LogLevel:"debug"}
