### ISSUE TITLE
Support correct file ending in windows

### ISSUE THREAD

**Issue by jsturtevant** [BurntSushi/toml#262]
The file ending is hard coded for windows:

https://github.com/BurntSushi/toml/blob/a368813c5e648fee92e5f6c30e3944ff9d5e8895/encode.go#L510

Found this while working with containerd: https://github.com/containerd/containerd/issues/4381

**Comment by jsturtevant** [comment]
it doesn't look like the project is active but if it is let me know and I can open a fix for it.

**Comment by arp242** [comment]
This is just for encoding/writing a file, no? I believe that most Windows tools should support `\n` line endings now (even Notepad!) TOML doesn't disallow `\r`, parsing them works fine, but I'm not sure if there's any practical value in ever writing them?

I think the problem you have is that the file is in Windows "unicode", which us UTF-16/UCS-2. TOML is pretty clear that only UTF-8 is supported. In #276 a clearer error for that was added, so I think that should fix it.
