### ISSUE TITLE
deprecate this package

### ISSUE THREAD

**Issue by qlcom** [BurntSushi/toml#265]
TOML is now at v1.0.0 rc.1 but this package is only v0.4 compatible and development has stopped.

**Comment by qlcom** [comment]
@BurntSushi

**Comment by qlcom** [comment]
I requesting you to response @BurntSushi

**Comment by qlcom** [comment]
response @BurntSushi

**Comment by BurntSushi** [comment]
Please stop pinging me. I don't owe you a response.

People using this package can make their own determination about whether it's appropriate to use or not.

**Comment by qlcom** [comment]
ok.
