### ISSUE TITLE
Use the Encode function to Encode structures as "" (multi-line literal strings wrapped in three single quotes)

### ISSUE THREAD

**Issue by fengcunwu** [BurntSushi/toml#269]
golang 
type Item struct {
	Type  RedisKeyType `toml:"type"`
	Key   string       `toml:"key"`
	Value interface{}  `toml:"value"`
}
encode-------
toml 
type="string"
key="test"
value=''' 
{}
'''

**Comment by ofey404** [comment]
I need this feature too! Besides, it's not hard to implement one, maybe I can submit a PR.

**Comment by arp242** [comment]
This is a duplicate of #64
