### ISSUE TITLE
Relax type checking to allow heterogenous arrays

### ISSUE THREAD

**Issue by ear7h** [BurntSushi/toml#305]
Heterogeneous arrays were added in [version 1.0.0-rc.1](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#100-rc1--2020-04-01).

I'm willing to submit a pr/tests but wanted to know what the maintainers' thoughts are since this is could be considered a breaking change

**Comment by arp242** [comment]
Yeah, I thought this was already fixed/added before I took over maintainership, but it seems that I misread something and that it's not.

Coincidentally, I was actually working on this just now. The decoding part is pretty easy and just consists of deleting some code; the encoding part is a bit more involved; I have something that almost-but-not-quite-yet works 😅

Either way, should be added soon™.

**Comment by ear7h** [comment]
Sounds good, thanks!
