### ISSUE TITLE
Tagged anonymous structs can’t be parsed if the type is unexported

### ISSUE THREAD

**Issue by numberZero** [BurntSushi/toml#309]
An example very similar to that in https://github.com/pelletier/go-toml/issues/508 panics:
```go
package main

import (
	"fmt"
	bToml "github.com/BurntSushi/toml"
)

var b = []byte(`[head]
title = "This is a title"`)

type text struct {
	head `toml:"head"`
}

type head struct {
	Title string `toml:"title"`
}

func main() {
	t2 := text{}
	bToml.Unmarshal(b, &t2)
	fmt.Println("btoml title:", t2.Title)
}
```
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x4ded40, 0xc0000103b0, 0x1d9, 0xc000022001, 0x51b360, 0x4dedc0)
        <...>/go/src/reflect/value.go:1027 +0x169
reflect.Value.Interface(...)
        <...>/go/src/reflect/value.go:1016
github.com/BurntSushi/toml.isUnifiable(0x4ded40, 0xc0000103b0, 0x1d9, 0x4ded40)
        <...>/github.com/BurntSushi/toml/decode.go:501 +0x59
github.com/BurntSushi/toml.(*MetaData).unifyStruct(0xc00004de80, 0x4dc280, 0xc000072150, 0x4dedc0, 0xc0000103b0, 0x199, 0xc0000103b0, 0xc00006ecd0)
        <...>/github.com/BurntSushi/toml/decode.go:262 +0x2a5
github.com/BurntSushi/toml.(*MetaData).unify(0xc00006ee80, 0x4dc280, 0xc000072150, 0x4dedc0, 0xc0000103b0, 0x199, 0x60, 0x1)
        <...>/github.com/BurntSushi/toml/decode.go:209 +0x8d4
github.com/BurntSushi/toml.Decode(0xc00001c0e0, 0x20, 0x4d3960, 0xc0000103b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <...>/github.com/BurntSushi/toml/decode.go:123 +0x3dd
github.com/BurntSushi/toml.Unmarshal(...)
        <...>/github.com/BurntSushi/toml/decode.go:25
main.main()
        <...>/test1.go:21 +0x9c
exit status 2
```
It works well when using `Head` instead of `head`, or omitting the tag (and the section header correspondingly).

**Comment by arp242** [comment]
The reason for this is that the struct is read from another package (`toml` in this case), and if it's not exported then it can't read it.

So you need to export it: this is how all encoders/decoders in Go work, and there isn't really anything that can be done about this.

**Comment by numberZero** [comment]
To your explanation, the example from pelletier/go-toml#508 wouldn’t work either. But it works, specifically with this library (and doesn’t work with pelletier’s btw). The only difference I see is that the anonymous struct has a tag in my example but not in that one. Why does that matter?

**Comment by pelletier** [comment]
Just found this thread while doing some optimizations on go-toml's struct analysis. go-toml v2 supports anonymous unexported structs when un/marshaling: https://github.com/pelletier/go-toml/blob/2d759c598682adbe4f6d69a75c996fe47437a75f/unmarshaler.go#L1105-L1130
