### ISSUE TITLE
Assign to new elements to decoded struct with primitives

### ISSUE THREAD

**Issue by iphands** [BurntSushi/toml#310]
Hi all, Im a bit lost this might not be a bug.
https://github.com/iphands/scratch/blob/main/go/toml_test/main.go

Im trying to parse a containerd.toml into a struct and then add to the plugins section.
However in the posted example I get a:
```
# command-line-arguments
./main.go:31:28: cannot use TestPlugin{...} (type TestPlugin) as type "github.com/pelletier/go-toml".Tree in assignment
```

Is there something I can do to change my struct into a toml.Primitive and proceed?
Thanks and sorry if this is obvious... I searched around but ran in to nothing helpful.

**Comment by arp242** [comment]
You're assigning the wrong type, pretty much as the error says:

> cannot use TestPlugin{...} (type TestPlugin) as type "github.com/pelletier/go-toml".Tree in assignment

It wants that `Tree` type, but you're using `TestPlugin`.

This isn't really related to this package.
