### ISSUE TITLE
bare carriage return in whitespace should be an error

### ISSUE THREAD

**Issue by moorereason** [BurntSushi/toml#316]
Given a TOML document of `\r`, should the parser return an error?  It doesn't appear to be valid whitespace based upon the ABNF:

```abnf
newline =  %x0A     ; LF
newline =/ %x0D.0A  ; CRLF
```

**Comment by arp242** [comment]
This is pretty much the same underlying issue as #317 (you had no way of knowing this), so I'll close this as a duplicate of that one.
