### ISSUE TITLE
no error on NULL byte

### ISSUE THREAD

**Issue by moorereason** [BurntSushi/toml#317]
Playing with Go dev.fuzz and found an odd one.  `[abc]\x00` errors, but `[abcd]\x00` doesn't.

https://play.golang.org/p/m3GHDLMYXrA
```go
toml.Unmarshal([]byte("[abcd]\x00\na=b"), &v)
```

**Comment by arp242** [comment]
It checks [the first six bytes for NULL](https://github.com/BurntSushi/toml/blob/master/parse.go#L56-L65) as a "quick check" to see if the file is in UTF-16, mostly to give a more user-friendly error message. That explains why you get the error for one string and not the other :-)

It checks for control characters inside various tokens (strings, keys, etc.) but it just reads over it outside of that; that should be fixed.
