### ISSUE TITLE
Check all the keys are found in toml

### ISSUE THREAD

**Issue by FlorianRuen** [BurntSushi/toml#319]
HI there,

I'm using this library to decode a toml file into structs, but I need something more to check if all the keys are present in the file. I'm explaining.

We are two different person who develop and who release the software in production, and sometimes we forgot to update the config.toml with new keys / values. In this case, I want to fire an error, because not all the keys are decoded.

For example, something if not all the keys from the structs are found in the file, fire an error that I will handle. Or something that can check after decoding if there is no nil values inside (that will say the key isn't found in the file for example)

There is something like using the DecodeFile function or not ? Maybe a workaround is evisageable ?

Regards,
Florian

**Comment by arp242** [comment]
I'll assume this issue is solved; feel free to get back to me if it's not and we can look further.
