### ISSUE TITLE
Require 2-digit hour for local time

### ISSUE THREAD

**Issue by moorereason** [BurntSushi/toml#320]
Given `a=1:32:00`, this package returns a valid time-local value instead of returning an error.

### Reproduction
https://play.golang.org/p/fciY3UVyoT6

```go
toml.Unmarshal([]byte("a=1:32:00"), &v)
```
Or using the `toml-test` decoder:

```
$ echo "a=1:32:00" | toml-test-decoder2
{
  "a": {
    "type": "time-local",
    "value": "01:32:00"
  }
}
```

**Comment by arp242** [comment]
This is actually an issue for all datetimes, not just local time; the problem is that `15` in `time.Parse` accepts both `01` and `1`. There doesn't seem any way to require a leading zero.

**Comment by arp242** [comment]
I'm somewhat leaning towards just leaving it like this; writing times like "1:12:13" isn't *too* uncommon, it will always encode things as "01:12:13" so it won't cause issues with other decoders, and even though it's not fully spec-compliant I don't really see any problems with it. Might be worth discussing modifying the specification on this.

**Comment by moorereason** [comment]
I'm simply reporting issues I've found while doing differential fuzzing against this package and `go-toml` and `toml.dart`.

But I'm in favor of following the TOML spec. As reported, this issue doesn't follow the spec.
