### ISSUE TITLE
Allow two trailing quotation marks inside multiline basic string

### ISSUE THREAD

**Issue by moorereason** [BurntSushi/toml#324]
**Describe the bug**
Given `0="""\""""""`, toml complains `Error decoding TOML: Near line 1 (last key parsed '0'): unexpected '""""""'`.

**To Reproduce**
https://play.golang.org/p/XlRqXMXzR1K
```go
toml.Unmarshal([]byte("0=\"\"\"\\\"\"\"\"\"\""), &v)
```

**Expected behavior**
I expected the result to 3 quotations marks (`"""`).

The spec reads:
> You can write a quotation mark, or two adjacent quotation marks, anywhere inside a multi-line basic string.

One of the examples from the TOML v1.0.0 spec is close to this issue, but the trailing period avoids the code path in question:

```toml
str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""
```
If the period is replaced with one quotation mark, it parses correctly.  If the period is replaced with two quotation marks (https://play.golang.org/p/7sU_b8ZZvlM), this issue is triggered.

**Versions**
 - toml: e0af6a256822c45317ce8c57358ec8ef186e6abc
 - go version go1.17.1 linux/amd64

**Additional context**
Found while doing differential fuzzing against go-toml.

**Comment by moorereason** [comment]
Thinking about this a little closer, I think the issue is the preceding escaped quotation mark that's tripping up the parser.  The error message complains about six quotation marks when the first one should be ignored due to escaping.

Should we add a test case for this to the toml-test suite?

**Comment by arp242** [comment]
> Should we add a test case for this to the toml-test suite?

Yeah, probably; same for most of the other issues you created. I have some other work in the pipeline for this library I'll finish up first, and then I'll look at the issues you created, adding test cases to toml-test as needed.

**Comment by arp242** [comment]
Looks like this got fixed some time ago; the test I added to toml-test passes anyway.
