### ISSUE TITLE
Using a TextUnmarshaler in a map value doesn't work

### ISSUE THREAD

**Issue by GarryGaller** [BurntSushi/toml#334]
Could you explain how to apply this
```go
func (d *duration) UnmarshalText(text []byte) (err error) {
	d.Duration, err = time.ParseDuration(string(text))
	return err
}
```
to
```go
type httpclient struct {
    Timeouts map[string]string
}
```
to be able to write in the config like this

```
[httpclient.timeouts]
client = "60s"
2XX = "50ms"
3XX = "1000ms"
4XX = "2000ms"
5XX = "5000ms"
```
?

**Comment by arp242** [comment]
Did you try `map[string]duration`? I think that should work, but I didn't try it.

**Comment by GarryGaller** [comment]
Yeah, I tried that.
But then all key type becomes duration, which is incompatible with time.Duration for passing values to functions like time.Sleep, etc.

**Comment by arp242** [comment]
The key is a string, not a `duration`(?) And you can pass `duration.Duration` to `time.Sleep()`.

It would be helpful if you could more clearly describe what exactly isn't working with some example.

**Comment by GarryGaller** [comment]
If you create a minimal example, there is an error: type mismatch for main.duration: expected table but found string
(and my code didn't compile at all for a slightly different reason)

```
package main

import (
    "github.com/BurntSushi/toml"
    "time"
    "fmt"
    "log"
)

type Config struct {
    HttpClient  httpclient
}
type httpclient struct {
    Timeouts   map[string]duration
}

type duration struct {
	time.Duration
} 

func (d *duration) UnmarshalText(text []byte) (err error) {
	d.Duration, err = time.ParseDuration(string(text))
	return err
}


func main() {
    var conf Config
    if _, err := toml.DecodeFile("toml_config.toml", &conf); err != nil {
         log.Fatal(err)
    } else {
        fmt.Printf("%v\n", conf)
        fmt.Printf("%v\n", conf.HttpClient.Timeouts)
    }
}
```

config_toml.toml
```
[httpclient.timeouts]
client = "60s"
```

Output error:

**Comment by arp242** [comment]
Right; here's a bit of a clearer example:

	type duration struct{ time.Duration }

	func (d *duration) UnmarshalText(text []byte) (err error) {
		d.Duration, err = time.ParseDuration(string(text))
		return err
	}

	func main() {
		t := `
			[httpclient.timeouts]
			client = "60s"
			2XX = "50ms"
			3XX = "1000ms"
			4XX = "2000ms"
			5XX = "5000ms"
		`

		{
			var conf struct {
				HttpClient struct{ Timeouts map[string]string }
			}
			_, err := toml.Decode(t, &conf)

			// {{map[2XX:50ms 3XX:1000ms 4XX:2000ms 5XX:5000ms client:60s]}}
			fmt.Printf("%v\n%v\n\n", err, conf)
		}

		{
			var conf struct {
				HttpClient struct{ Timeouts map[string]duration }
			}
			_, err := toml.Decode(t, &conf)
			// toml: type mismatch for main.duration: expected table but found string
			fmt.Printf("%v\n%v\n", err, conf)
		}
	}

Outputs:

    <nil>
    {{map[2XX:50ms 3XX:1000ms 4XX:2000ms 5XX:5000ms client:60s]}}

    toml: type mismatch for main.duration: expected table but found string
    {{map[]}}

The `map[string]string` works, but `map[string]duration` doesn't with a rather odd error.

Might be related to #195 (?) Curiously, it does work if you use `UnmarshalTOML`:

    type duration struct{ time.Duration }

    func (d *duration) UnmarshalTOML(text interface{}) (err error) {
        d.Duration, err = time.ParseDuration(text.(string))
        return err
    }

Which outputs the expected:

    <nil>
    {{map[2XX:50ms 3XX:1000ms 4XX:2000ms 5XX:5000ms client:60s]}}

    <nil>
    {{map[2XX:50ms 3XX:1s 4XX:2s 5XX:5s client:1m0s]}}

So you can use that, although `UnmarshalText` should also work.

**Comment by GarryGaller** [comment]
> So you can use that, although UnmarshalText should also work.

Yes, UnmarshalTOML works for a small example. But only as long as we don't start applying values from map, or assign new values like time.Duration to map.
Here are the errors from my actual application.
Many functions turn out not to be ready to accept the custom type **duration**.
```
engine\engine.go:152:27: cannot use delayTime5XX (type config.duration) as type time.Duration in argument to time.Sleep
engine\engine.go:225:31: cannot use delayTime5XX (type config.duration) as type time.Duration in argument to time.Sleep
engine\engine.go:261:23: cannot use delayTime2XX (type config.duration) as type time.Duration in argument to time.Sleep
engine\engine.go:304:26: invalid operation: goTimeOut > 0 (mismatched types config.duration and int)
engine\engine.go:305:27: cannot use goTimeOut (type config.duration) as type time.Duration in argument to time.Sleep
engine\handlers.go:198:27: cannot use requestTimeOut (type config.duration) as type time.Duration in argument to context.WithTimeout
engine\handlers.go:324:27: cannot use requestTimeOut (type config.duration) as type time.Duration in argument to context.WithTimeout
engine\handlers.go:475:27: cannot use requestTimeOut (type config.duration) as type time.Duration in argument to context.WithTimeout
engine\handlers.go:869:27: cannot use requestTimeOut (type config.duration) as type time.Duration in argument to context.WithTimeout
engine\sessionid.go:118:47: cannot use t.config.HttpClient.Timeouts["token_ttl"] (type config.duration) as type time.Duration in argument to token.TTL```

We need to somehow avoid creating a new type instead of time.Duration...

**Comment by GarryGaller** [comment]
Yes, of course, it will work if you write it that way:
time.Sleep(conf.HttpClient.Timeouts["client"].Duration) 

but I wouldn't want to rewrite everything...

**Comment by arp242** [comment]
You can use the `.Duration` field, e.g. with the example I posted above:

    n := time.Now().Round(time.Second)
    for _, d := range conf.HttpClient.Timeouts {
        fmt.Println(n, n.Add(d.Duration))
    }

Shows:

    2021-11-28 14:50:54 +0100 CET 2021-11-28 14:50:55 +0100 CET
    2021-11-28 14:50:54 +0100 CET 2021-11-28 14:50:56 +0100 CET
    2021-11-28 14:50:54 +0100 CET 2021-11-28 14:50:59 +0100 CET
    2021-11-28 14:50:54 +0100 CET 2021-11-28 14:51:54 +0100 CET
    2021-11-28 14:50:54 +0100 CET 2021-11-28 14:50:54.05 +0100 CET

Or alternatively, you can make `Timeouts` a custom `map[string]Duration` type with an unmarshal.

**Comment by GarryGaller** [comment]
OK, I used to pass my custom type .Duration field to the functions waiting for time.Duration.
Since there's no other way out.
But it's not very convenient.
Anyway, thank you for the clarification.

**Comment by arp242** [comment]
Like I said, you can use a custom map type; I actually do something similar over here: https://github.com/arp242/z18n/blob/master/finder/finder.go#L61

Here's an example for your durations, which does what you want if I understand correctly:

```go
type timeouts map[string]time.Duration

func (t *timeouts) UnmarshalTOML(m interface{}) error {
	mm, ok := m.(map[string]interface{})
	if !ok {
		return fmt.Errorf("wrong type: %T", m)
	}

	tt := *t
	if tt == nil {
		tt = make(map[string]time.Duration)
	}

	for k, v := range mm {
		d, err := time.ParseDuration(v.(string))
		if err != nil {
			return err
		}
		tt[k] = d
	}
	*t = tt

	return nil
}

func main() {
	t := `
		[httpclient.timeouts]
		client = "60s"
		2XX = "50ms"
		3XX = "1000ms"
		4XX = "2000ms"
		5XX = "5000ms"
	`

	var conf struct {
		HttpClient struct{ Timeouts timeouts }
	}
	_, err := toml.Decode(t, &conf)
	fmt.Printf("%v\n%v\n", err, conf)

	n := time.Now().Round(time.Second)
	for _, d := range conf.HttpClient.Timeouts {
		fmt.Println(n, n.Add(d))
	}
}
```

**Comment by GarryGaller** [comment]
Thanks a lot :-)
That's exactly what I wanted but couldn't come up with.

**Comment by arp242** [comment]
The underlying issue of map values not working should be fixed now.
