### ISSUE TITLE
Minimum Go release for tests is 1.16

### ISSUE THREAD

**Issue by moorereason** [BurntSushi/toml#340]
The existing package tests only work in Go 1.16+.

With Go 1.15:
```
sh$ go test ./...
internal/toml-test/runner.go:7:2: package embed is not in GOROOT (/home/cmoore/sdk/go1.15.10/src/embed)
internal/toml-test/runner.go:11:2: package io/fs is not in GOROOT (/home/cmoore/sdk/go1.15.10/src/io/fs)
```
The `embed` and `io/fs` packages were added to the stdlib in Go 1.16.

Example from [the CI framework](https://github.com/BurntSushi/toml/runs/4785890080?check_suite_focus=true).

**Comment by arp242** [comment]
Fixed it.
