### ISSUE TITLE
Skipped members generate invalid type error

### ISSUE THREAD

**Issue by davidnewhall** [BurntSushi/toml#345]
Hello! I'm curious if this code is expected to work. It's the smallest example I could come up with that reproduces my error. Some of my struct members are functions, and they have the `-` tag as shown here. I get an error trying to encode these structs. Is this a bug, or expected? Thanks!

```
package main

import (
	"bytes"
	"github.com/BurntSushi/toml"
)

func main() {
	var buf bytes.Buffer

	test := &struct {
		Func func() `toml:"-"`
	}{
		Func: main,
	}

	err := toml.NewEncoder(&buf).Encode(test)
	if err != nil {
		println(err.Error())
	}
}
// Output:
// unsupported type: func
```

**Comment by arp242** [comment]
> Is this a bug, or expected? Thanks!

Neither; I just don't think it ever came up before.

I can't think of any reason why it shouldn't ignore this off-hand.
