### ISSUE TITLE
Integration with google oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [BurntSushi/toml#364]
Hi, I would like to help integrate this project into [oss-fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8279, it contains necessary logic from an OSS-Fuzz perspective to integrate BurntSushi/toml. This includes developing initial fuzzers as well as integrating into OSS-Fuzz.

- Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- If you would like to integrate, could I please have an email(s), it must be associated with a Google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by arp242** [comment]
Thanks; this is pretty neat!

I can't create a Google account because I don't have a mobile phone though, so if that's a hard requirement...

**Comment by arp242** [comment]
> i'll keep an eye on bug reports or crashes and file them here.. :)

Alrighty; thanks.
