### ISSUE TITLE
omitempty incorrectly looks at values behind pointers

### ISSUE THREAD

**Issue by joukewitteveen** [BurntSushi/toml#371]
[isEmpty is called on a fully dereferenced struct](https://github.com/BurntSushi/toml/blob/v1.2.0/encode.go#L507), but if the original field type of the struct was a pointer to a struct, then omitempty should be taken to mean "drop if nil, otherwise output". In other words: isEmpty on any pointer type should return true precisely when the pointer is nil. This is currently not what happens because [the field value is fully dereferenced](https://github.com/BurntSushi/toml/blob/v1.2.0/encode.go#L493).

This is a leftover from #360. The issue is demonstrated by the failure in #370.

**Comment by arp242** [comment]
I can confirm it broke in the v1.2.0 release; it works as expected in v1.1.0. It's probably d138d7a2 that introduced this; that changed it to always call `eindirect`.

Not sure yet when I'll look at this, but happy to review and accept patches in the meanwhile.
