### ISSUE TITLE
toml crashs when it stumbles over a *flag.FlagSet

### ISSUE THREAD

**Issue by HeikoSchlittermann** [BurntSushi/toml#382]
The following code crashes with go1.20 and toml v0.3.1:
```
package main

import (
        "flag"
        "os"

        "github.com/burntsushi/toml"
        //toml "github.com/pelletier/go-toml/v2"
)

func main() {
        o := struct {
                *flag.FlagSet `toml:"-"`
        }{
                FlagSet: flag.CommandLine,
        }
        toml.NewEncoder(os.Stdout).Encode(o)
}
```
I didn't try yet to debug it further, for now "pelletier" does its job, but maybe it is something to be worked on.

Thanks for providing the package.
-- 
Heiko

**Comment by arp242** [comment]
v0.3.1 is pretty old and here have been many changes since then; did you try it with a newer version?

**Comment by arp242** [comment]
I tried running it myself with v1.2.1 and it seems to work fine:

    % go run main.go
    [no output, as it's a blank document]

Note that the import path should be `github.com/BurntSushi/toml` (with capitals); if you don't you get an error:

    % go get github.com/burntsushi/toml
    go: github.com/burntsushi/toml@v1.2.1: parsing go.mod:
            module declares its path as: github.com/BurntSushi/toml
                    but was required as: github.com/burntsushi/toml

Which is probably why you're using the older version, as that's the last version before a go.mod was added.

**Comment by HeikoSchlittermann** [comment]
Thanks for the clarification. Unfortunately the update mechanism (`go get -u`) doesn't seem to work for that case change.
After changing the case of the import path manually (as you suggested), it works as expected with the latest version of the module.
