### ISSUE TITLE
Support for default struct tag

### ISSUE THREAD

**Issue by sarathsp06** [BurntSushi/toml#385]
I couldn't find support for specifying default values in struct tags.  If not added it  would be a good addition in my opinion and I am happy to make a pull request with the same

**Comment by arp242** [comment]
Struct tags are just for providing name aliases; I'm not in favour of expanding it to other features. It gets pretty messy quickly; what do you do with an int field that has a string as a default? Go has a type checker for stuff like that, but you can't typecheck struct tags. It's also much too easy to typo or get it wrong in other ways.

If you want default values, you can use something like:

    d := MyStruct{Field: "value"}
    toml.Decode(tomlData, &d)

**Comment by SharkFourSix** [comment]
Lmao, this is insane. When you have a big struct with nested slices/arrays how would you initialize any of them without knowing the size?
