### ISSUE TITLE
TOML file not deserializing into struct

### ISSUE THREAD

**Issue by vibeisveryo** [BurntSushi/toml#386]
Hi, I've been attempting to deserialize a TOML file into my custom map to structs, closely following the [decode example](https://godocs.io/github.com/BurntSushi/toml#example-Decode) given in the documentation. However, it reads the file, and apparently does actually correctly parse the content, but returns zero-valued structs:
	package main

	import (
		"fmt"
		"github.com/BurntSushi/toml"
	)

	type configMap map[string]server

	type server struct {
		host     string `toml:"hostname"` // referred to as hostname in config file for backwards compatibility
		port     int    `toml:"port"`
		password string `toml:"password"`
	}

	const configData = `# RCON Config
	# You can add servers, removing the # indicating comments, as below
	# [someservername]
	# hostname = 172.0.0.1
	# port = 27015
	# password = somepassword

	[test]
	hostname = "example.com"
	port = 12345
	password = "myPassword"

	[test2]
	hostname = "example.com"
	port = 12346
	password = "myPassword"

	[test3]
	hostname = "example.com"
	port = 12347
	password = "myPassword"`

	func main() {
		// Decode config info
		var config configMap
		_, err := toml.Decode(configData, &config)
		if err != nil {
			panic(err)
		}
		fmt.Println(config)
	}

Minimal example of my code here ^ produces output:
```map[test:{ 0 } test2:{ 0 } test3:{ 0 }]```

According to the debugger it does actually read/parse the content of the blob:
![image](https://user-images.githubusercontent.com/27565096/227564410-9c8782ba-5548-4d8e-940b-ccca7f802555.png)

But it doesn't materialize in the final product. Am I doing something wrong here?

**Comment by arp242** [comment]
You need to export the fields, or the toml package won't be able to access them:

	type server struct {
		Host     string `toml:"hostname"`
		Port     int    `toml:"port"`
		Password string `toml:"password"`
	}
