### ISSUE TITLE
awaiting v1.2.2 release

### ISSUE THREAD

**Issue by kmuto** [BurntSushi/toml#389]
Hi,
I'm awaiting new toml release to get fix #381 .
Could you consider to release?

**Comment by arp242** [comment]
Ideally I'd like to solve the few outstanding bugs first.

In the meanwhile, you should be able to use  `go get github.com/BurntSushi/toml@master` (or a specific commit) – there isn't really any downside to this a far as I know.

**Comment by arp242** [comment]
I tagged v1.3.0
