### ISSUE TITLE
proposal: allow decoding into embedded maps

### ISSUE THREAD

**Issue by pauhull** [BurntSushi/toml#393]
Hi!

Currently it is possible to decode following file:
```toml
[a.a]
foo = "bar"

[a.b]
foo = "baz"
```

Into the following struct:
```go
type Config struct {
    A map[string]struct {
        Foo string `toml:"foo"`
    } `toml:"a"`
}
```

And you would receive following result:
```go
{A:map[a:{Foo:bar} b:{Foo:baz}]}
```

---

Now imagine that you also wanted some settings under the 'a' section, like this:
```toml
[a]
foo_bar = 42

[a.a]
foo = "bar"

[a.b]
foo = "baz"
```

As far as I can tell, this is currently not possible to decode with this library (please correct me if I'm wrong). To address this, it would be nice to have an embedded map in the struct to decode to that would hold the data. The struct could look something like this:
```go
type EmbeddedMap map[string]struct {
    Foo string `toml:"foo"`
} `toml:"a"`

type Config struct {
    A struct { 
        EmbeddedMap        
        /* extra properties go here */ 
        FooBar int `toml:"foo_bar"`
    } `toml:"a"`
}
```

This would result in following data:
```go
{A:{EmbeddedMap:map[a:{Foo:bar} b:{Foo:baz}] FooBar:42}}
```

Please let me know if this is feasible (or even possible) or if there is an existing alternative. Thanks!

**Comment by arp242** [comment]
This seems to work:

	package main

	import (
		"fmt"

		"github.com/BurntSushi/toml"
	)

	type Map map[string]struct {
		Foo string `toml:"foo"`
	}
	type Config struct {
		A struct {
			Map    `toml:"map"`
			FooBar int `toml:"foo_bar"`
		} `toml:"a"`
	}

	func main() {
		var c Config
		_, err := toml.Decode(`
			a.foo_bar = 4
			a.map.xxx = {foo = "zxc"}
			[a.map.yyy]
			foo = "asd"
		`, &c)
		fmt.Println(err)
		fmt.Println(c.A.FooBar)
		fmt.Println(c.A.Map)
	}

Outputs:

    <nil>
    4
    map[xxx:{zxc} yyy:{asd}]

Although I have to say I find this structure rather confusing, but it's not really clear to me what your use case is.

Either way, it does work.
