### ISSUE TITLE
Multiple tags for member

### ISSUE THREAD

**Issue by apprehensions** [BurntSushi/toml#399]
Would it be possible for one struct member to have two toml tags? eg.
```go
type Foo struct {
    // Bar is deprecated 
    Baz `toml:"bar,baz"`
}
```

**Comment by arp242** [comment]
You can't do this.

How would you expect this to behave?

**Comment by apprehensions** [comment]
I suppose to take baz's information and always prefer it over bar, if it has no information or is nil
