### ISSUE TITLE
Fuzz failed round trip

### ISSUE THREAD

**Issue by manunio** [BurntSushi/toml#407]
Hi, I received an oss-fuzz report with the following error message:

```
panic: failed round trip: toml: line 1 (last key "g"): invalid datetime: "2413-01-02T17:04:07+100:05"
```
The above panic was caused by fuzz target with the following input:
`g=2413-01-02 17:04:07+99:65`

at:
https://github.com/BurntSushi/toml/blob/3203540e6e1b096e45b3f614caccb7560be1a87c/ossfuzz/fuzz.go#L30

originated here by second `Decode`:
https://github.com/BurntSushi/toml/blob/3203540e6e1b096e45b3f614caccb7560be1a87c/parse.go#L376
Can this be similar to go-toml's:
https://github.com/pelletier/go-toml/issues/913

Input file:
[clusterfuzz-testcase-minimized-fuzz_toml-5085441777795072.txt](https://github.com/BurntSushi/toml/files/15268781/clusterfuzz-testcase-minimized-fuzz_toml-5085441777795072.txt)

**Comment by arp242** [comment]
It's kind of a bug in Go; let's see what comes rolling out of the bug report before I hack workarounds: https://github.com/golang/go/issues/67470

**Comment by arp242** [comment]
Yeah, that's fine. I don't expect I'll do another release before Go 1.23 anyway.
