### ISSUE TITLE
Unmarshaling into a non-empty variable keeps the old data

### ISSUE THREAD

**Issue by hezhizhen** [BurntSushi/toml#415]
Here's my example:

```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/BurntSushi/toml"
)

type ApplicationConfig struct {
	ReusePodForBuild map[string]bool `toml:"reuse_pod_for_build"`
}

func main() {
	var config *ApplicationConfig

	go func() {
		for {
			bs, err := os.ReadFile("test.toml")
			if err != nil {
				panic(err)
			}
			fmt.Println(string(bs))
			err = toml.Unmarshal(bs, &config)
			if err != nil {
				panic(err)
			}
			fmt.Printf("%+v\n", config)
			time.Sleep(time.Second * 5)

		}
	}()

	select {}
}
```

and below is `test.toml`: 

```toml
[reuse_pod_for_build]
"a" = true
"b" = false
```

I ran the main.go first and then deleted the line of `"b" = false` and below is the output:

```[reuse_pod_for_build]
"a" = true
"b" = false

&{ReusePodForBuild:map[a:true b:false]}
[reuse_pod_for_build]
"a" = true
"b" = false

&{ReusePodForBuild:map[a:true b:false]}
[reuse_pod_for_build]
"a" = true

&{ReusePodForBuild:map[a:true b:false]}
[reuse_pod_for_build]
"a" = true

&{ReusePodForBuild:map[a:true b:false]}
^Csignal: interrupt
```

I expect that `config` variable is completely the same as the content of `test.toml` but it keeps the deleted keys and their values.

**Comment by arp242** [comment]
> I expect that config variable is completely the same as the content of test.toml but it keeps the deleted keys and their values.

That's intentional. It's also useful: to set default values, or to unmarshal only *some* values.

You could maybe argue it makes more sense to clear the values, but this is how it works now and changing it would be incompatible and break people's programs that rely on the current behaviour, so outright changing it isn't really an option.

We could maybe add some some option for it. Although I think just creating a new config struct or clearing that map should be easy?

**Comment by hezhizhen** [comment]
> > I expect that config variable is completely the same as the content of test.toml but it keeps the deleted keys and their values.
> 
> That's intentional. It's also useful: to set default values, or to unmarshal only _some_ values.
> 
> You could maybe argue it makes more sense to clear the values, but this is how it works now and changing it would be incompatible and break people's programs that rely on the current behaviour, so outright changing it isn't really an option.
> 
> We could maybe add some some option for it. Although I think just creating a new config struct or clearing that map should be easy?

After realizing it, the easiest way to fix it to use a new variable every time to be unmarshaled into.

Maybe it's better to state it clearly in comments.
