### ISSUE TITLE
Why is pkg.go.dev page out of date?

### ISSUE THREAD

**Issue by FeldrinH** [BurntSushi/toml#416]
Searching for this package brings up its documentation at https://pkg.go.dev/github.com/burntsushi/toml, but confusingly, that page seems to currently show documentation for v0.3.1, which it claims is the latest version. What is going on here?

**Comment by arp242** [comment]
Before Go modules were added casing wasn't enforced when you did `go get`, and GitHub will work with any casing variant. I guess I could request it to be removed, but some people use the lower-case variant, and removing it from the Go module cache will break that: https://github.com/search?q=%2F%28%3F-i%29github.com%5C%2Fburntsushi%5C%2Ftoml%2F&type=code

**Comment by FeldrinH** [comment]
So https://pkg.go.dev/github.com/BurntSushi/toml is the correct, up to date page? Honestly, I'm not sure what should be done, but it is a little confusing that Google seems to find only the old outdayed page.

**Comment by arp242** [comment]
> So https://pkg.go.dev/github.com/BurntSushi/toml is the correct, up to date page? 

Yes, that's the correct one (and only correct one).

I filed an issue about it here: https://github.com/golang/go/issues/68357
