### ISSUE TITLE
Bump go.mod ?

### ISSUE THREAD

**Issue by udf2457** [BurntSushi/toml#424]
I see your `go.mod` is currently "stuck" at 1.18.

Two reasons:

1.  keeping in-line with [Go release policy](https://go.dev/doc/devel/release) of "current and two prior"
2. the version of Go referenced is not cosmetic. Keeping it up to date has many benefits [as outlined here](https://go.dev/ref/mod) in terms of access to new language features and benefiting from improvements in compiler behaviour.

**Comment by arp242** [comment]
This library is compatible with Go 1.18. I see no benefit in increasing this "just because". People can and do run older Go versions.
