### ISSUE TITLE
Short format of structures naming

### ISSUE THREAD

**Issue by gitchander** [BurntSushi/toml#428]
In my config I have next part:
```
...
[log-config]
   log-level = "debug"
      [log-config.writer-config]
         [log-config.writer-config.file-config]
            compress = true
...

```

Name for struct "file-config" is too large [log-config.writer-config.file-config].
Is there possible to make shortest name without all includes (like [file-config]) ?

**Comment by arp242** [comment]
> Is there possible to make shortest name without all includes (like [file-config]) ?

No, the TOML file format doesn't support that. You should probably use less nesting if you find it inconvenient.

The repo to discuss the TOML file format is at https://github.com/toml-lang/toml by the way. This has been discussed a few times, and people generally agreed to not change things.
