### ISSUE TITLE
Unmarshal with default values

### ISSUE THREAD

**Issue by azr** [BurntSushi/toml#47]
Hello there,

Would that be a bad idea to have defaults when no information is provided ? Something like : 

```
type Server struct {
    Url		string
    Port	int `toml:port,default=80` 
}
```

Or would that default be done in the code ?

We could also have another toml file containing the default values to initialize the types with.

**Comment by jszwedko** [comment]
@BurntSushi setting defaults for nested structs that are arrays wouldn't be possible by presetting values though. E.g. if I wanted to default the server port to 80 for all servers.

**Comment by jszwedko** [comment]
And it is impossible to know afterwards whether a value was explicitly set with the zero value (e.g. 0 for integers and false for booleans) or just left out of the blob. Given these things, I think it'd be nice to support setting the default in the struct field tags.

**Comment by cespare** [comment]
I'm opposed to this change. If you have some kind of complex config like that, I think you're better off writing some kind of merge function to copy the decoded data into your default config structure.

Alternatively, you could use the metadata returned by Decode to learn which fields weren't set, and set them to their defaults.

In any case, shoving data into the struct tag seems like a fragile hack.
