### ISSUE TITLE
decoding table arrays need to be handled better

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/toml#49]
The following produces a runtime error:

```go
package main

import (
	"fmt"
	"log"

	"github.com/BurntSushi/toml"
)

type Server struct {
	Url  string
	Port int
}

type Host struct {
	Servers []Server
}

var blob = `
[Host]
[[Servers]]
Url = "http://burntsushi.net"
Port = 8080

[[Servers]]
Url = "http://github.com"
Port = 1234
`

func main() {
	config := Host{
		Servers: []Server{
			{
				Url:  "http://google.com",
				Port: 80,
			},
		},
	}
	if _, err := toml.Decode(blob, &config); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%#v\n", config)
}
```

This is because (I think) the default value. The decoder is probably checking if it's not nil, and then just assuming that it is the right size. It should be smarter. (Just appending isn't quite right either, because I think it should overwrite the default value. But I should probably check the behavior of the standard library decoders before implementing that.)

**Comment by cespare** [comment]
Fixed by #84.
