### ISSUE TITLE
[enhancement] support ISO8601 offsets

### ISSUE THREAD

**Issue by kevinburke** [BurntSushi/toml#58]
For example, if I type `date --iso-8601=seconds` using the GNU date program, I get the output

    2014-08-13T16:46:08-0700

It would be nice if this was parsed properly into a Time object, instead the code generates:

    Near line 4, key 'date': Near line 4: Expected 'Z' in ISO8601 datetime, but found '-' instead.

Here's the relevant piece of code:

```go
func lexDateAfterYear(lx *lexer) stateFn {
	formats := []rune{
		// digits are '0'.
		// everything else is direct equality.
		'0', '0', '-', '0', '0',
		'T',
		'0', '0', ':', '0', '0', ':', '0', '0',
		'Z',
	}
	for _, f := range formats {
		r := lx.next()
		if f == '0' {
			if !isDigit(r) {
				return lx.errorf("Expected digit in ISO8601 datetime, "+
					"but found %q instead.", r)
			}
		} else if f != r {
			return lx.errorf("Expected %q in ISO8601 datetime, "+
				"but found %q instead.", f, r)
		}
	}
	lx.emit(itemDatetime)
	return lx.pop()
}
```

**Comment by cespare** [comment]
Closing this issue in favor of #96.
