### ISSUE TITLE
support and examples for quoted keys?

### ISSUE THREAD

**Issue by zhenjl** [BurntSushi/toml#69]
Hi, does this support quoted strings such as

```
"127.0.0.1" = "value"
"character encoding" = "value"
"ʎǝʞ" = "value"
```

If so, is there an example on how that's used?

thx!

**Comment by zhenjl** [comment]
I think I got it figured out. Keys can be mapped to keys in a map, if they are quoted.

So something like 

```
[keys]
"abc" = [ "def", "ghi", "jkl" ]
```

can be mapped to a `map[string]map[string][]string`

**Comment by BurntSushi** [comment]
Yup, this was very recently added in https://github.com/BurntSushi/toml/commit/f706d00e3de6abe700c994cdd545a1a4915af060, so I haven't made any examples yet.

If you want to compile a few examples and submit a PR, that'd be great. :-)
