### ISSUE TITLE
Inline Table Support

### ISSUE THREAD

**Issue by ttacon** [BurntSushi/toml#70]
Hey, forgive me if I missed this. Recently, inline tables made it into the [spec](https://github.com/toml-lang/toml/pull/235), is this on the roadmap for being supported in this package soon (meaning what kind of priority would supporting inline tables be, if it's one at all)? Just wondering! Also, awesome library!

**Comment by BurntSushi** [comment]
Yes absolutely. This tracks the TOML spec (as does BurntSushi/toml-test).

I have a very limited number of hours (if that) each day to work on side projects such as these, but certainly, anything that causes an incompatibility between this repo and the TOML spec should be a priority.

Pull requests are always welcome, but I'll eventually get to it if nobody else does.

**Comment by ttacon** [comment]
Cool, I'm in a similar state - not enough time in the day for the side projects. If I can find some time though, I'll try to get to this - it's something I need for a side project.

**Comment by BurntSushi** [comment]
@ttacon Ah neat, that'd be awesome. My hope is that this can be done completely inside the lexer, which is reasonably simple once you've stared at it long enough. My fear is that this is wishful thinking and that the change will permeate into the parser, in which case, it will be quite a bit more hairy to implement.

**Comment by ttacon** [comment]
So adding it to the lexer took all of 2 minutes (the lexer was super nice to read :+1:). The parser, however, wasn't too happy with the changes... I'm going to try to make any changes minimal, but I probably won't have time to really dig into this until later unfortunately.

**Comment by BurntSushi** [comment]
That's awesome. If you want to put progress on to Github, I'll happily pull and piggy back off of you (if I get to it before you).

**Comment by ttacon** [comment]
Just put the lexer changes I'd made at PR #71.

**Comment by ttacon** [comment]
Hey, I just put up some more code to make parsing inline tables functional. However, I didn't spend enough time with parser.go to really understand what other information needs to be relayed (such as metadata about the file/keys/types/etc that this package keeps track of). TBH, I also wasn't sure what metadata you'd like extracted. Let me know what you think, I might have some more time this week to spend more time looking at it.

**Comment by ttacon** [comment]
@BurntSushi Have you had any time to think about what metadata should be included in this (with respect to inline tables)?

**Comment by ttacon** [comment]
@BurntSushi ^ bumpety bump :)

**Comment by BurntSushi** [comment]
@ttacon I'm sorry, but I'm still in the middle of it. I'm not sure when I'll be up for air. I haven't looked at your patch yet, so I'll just spit out a few things about meta data that I think I know.

The table `{a = {b = 5}}` should have precisely the same meta data as

```
[a]
b = 5
```

My hope is that your changes would happen at the lexer level and expose the table via `itemTableStart` and `itemTableEnd`. That way, the parser wouldn't have to change. But it looks like you added new items, which means the parser has to handle them.

Does that help at all?

**Comment by ttacon** [comment]
No problem! Just was wondering if you had seen the updates or not! I'll take another look at just making the changes in the lexer! Hopefully your research isn't keeping you too busy!

**Comment by ttacon** [comment]
Just pushed some changes to make metadata parsing work, and added a test to decode_test. Let me know if that's what you had in mind.

**Comment by gutenye** [comment]
any updates? inline-table is really a cool feature.

**Comment by jleclanche** [comment]
Anyone working on this?

**Comment by ttacon** [comment]
Ya, there's been an open PR in #71 for a while, just hasn't been merged.

**Comment by jleclanche** [comment]
@BurntSushi At a quick glance the code in #71 looks good. Could you review it?

**Comment by s7v7nislands** [comment]
any update?

**Comment by davecthomas** [comment]
+1. Looks like they're getting close...

**Comment by silasdavis** [comment]
Looking at that PR looks like it will support parsing inline tables from toml, but not generating them. I would like the ability to encode certain values within a toml configuration to be represented as inline tables. How difficult would this be to implement, is it something that would be accepted? I would anticipate implementing it by configuring the encoder to treat certain keys to be rendered as inline tables. I think it would be reasonable to enable inline-table style rendering recursively for all sub-tables of a specified table.

**Comment by binary132** [comment]
What about using the struct field tag `toml:"<your_key_name>,inline"` to cause the Marshal to render an inline table?  Seems a bit of an edge case that might fit well with field tags.

**Comment by cespare** [comment]
We now support decoding inline tables so this issue is resolved (and our TOML 0.4.0 support is complete).

I opened #160 for encoding inline tables.
