### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by tianon** [BurntSushi/toml#74]
Any way we could get a `v0.1.1` or `v0.2.0`, especially since some nice features like #61 have merged since the `v0.1.0` tag? :smile:

**Comment by Dr-Terrible** [comment]
:+1:

**Comment by cespare** [comment]
Is there something that depends on the git tags?

**Comment by tianon** [comment]
For distro packaging (Debian, Fedora, etc), Go dependencies have to be unbundled/unvendored, and it's easier to do that when the dependencies have and use some kind of versioning.  We do hacks to package snapshots for repos that don't use versioning, or for repos who don't want to tag intermediate changes, but it's much easier if upstreams are willing to provide some kind of versioning scheme (and makes it easier to say exactly which commit a particular package is built from without parsing the snapshot version strings we get to create).  Since there were previous version tags, I figured it was worth asking whether creating a new one would be amenable. :smile:

**Comment by onlyjob** [comment]
Tags/releases are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

See also

 * https://en.wikipedia.org/wiki/Software_versioning
 * http://semver.org/

**Comment by onlyjob** [comment]
Ping?

**Comment by cespare** [comment]
I feel that your packaging system should not depend on Go library authors tagging or versioning their repos, since that's not part of the typical Go toolchain and workflow. IMO, having end-user applications vendor their dependencies is the only sensible solution, and it's the one that's supported by the `go` tool itself. If you are trying to shoehorn Go applications into a packaging framework with a different opinion about how things should be done, you'll have to account for the fact that a Go package is just a VCS repo and nothing more. (And it sounds like that accounting has been done, judging by @tianon's comment about "hacks".)

That said, since there's already a version tag, I'm happy to add a new tag to indicate forward progress. I just added v0.2.0 at current master.

**Comment by onlyjob** [comment]
> I just added v0.2.0 at current master.

Thank you. :)

> I feel that your packaging system should not depend on Go library authors tagging or versioning their repos,

We are merely trying to promote best practice. We use mock-up date-based versions for libraries that do not do their own versioning (the "hacks").

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Versioning provides safety margin for situations like "ops, we've made a mistake but reverted problematic commit in master". Presumably tagged version/release is better tested/reviewed than random snapshot of "master" branch.

When security vulnerability is fixed the easiest way to promote updated library is through versioning. Claim that "latest is always the greatest" does not stand in practice yet that's exactly what lack of versioning suggests.

Downstream we can use versioning for automated tracking of new releases.

> since that's not part of the typical Go toolchain and workflow.

"Typical" Golang workflow promote ignorance and trash 20+ years of best practice in software engineering... :(

> IMO, having end-user applications vendor their dependencies is the only sensible solution, and it's the one that's supported by the go tool itself.

You are not considering context. For isolated application vendoring may be a "sensible solution"  even when developer dumps random snapshot of a library to source tree and never update it or track upstream changes until things break.

In GNU/Linux distributions like [Debian](http://debian.org) shipping coherent collection of software the only sensible way is to reuse dependency libraries. Think about harms of static linking: if you have 20+ applications "vendoring" different revisions of (for example) _libjpeg_ library how are you going to patch vulnerability in the latter? Backport (isolate) fix, re-vendor and try to re-build all applications? (Or maybe re-vendor latest version of the library and hope that all applications compile?) How much effort is that going to be and how long it is going to take?
Also, how many revisions of library you can effectively support?


> If you are trying to shoehorn Go applications into a packaging framework with a different opinion about how things should be done, you'll have to account for the fact that a Go package is just a VCS repo and nothing more.

Except that our (i.e. Debian) way of doing things have much longer history than Golang way.

It is not just difference of opinions. With packaging dependency libraries separately we are actually addressing certain deficiencies of Golang workflow. Like for instance running test suites for every dependency -- a something most often neglected for vendored libraries.

Reusable common libraries promote healthy ecosystem and communication between maintainers. There is better QA/CI as everything is built on more hardware architectures etc.

**Comment by cespare** [comment]
Three points.

1. This is just how things are in the Go world, so you'll have to deal with it regardless of what @BurntSushi and I do.
2. Sorry, but as a library developer, application developer, and deployer of Linux software I have found Go's static-linking-focused workflows to be massively headache-reducing compared to your decades of "best practices".
3. This is not the place to have this argument. Twitter might be that place, but I doubt you'll convince me :)

**Comment by onlyjob** [comment]
Static linking does not scale and it is effectively unsupportable/unmaintainable practice allowing developers to conveniently ignore evolution of dependencies.

I just wanted to mention one more thing: with Golang vendoring we've already seen situations where a large applications (e.g. Kubernetes) statically link with two or more different versions of a library through indirect dependencies. For example suppose application _D_ depends on libs _A_ and _B_ where _A_ depends on _C-1.1_ while _B_ depend on _C-1.5_ and _C_ library is sub-vendored twice under _A_ and _B_ that a both vendored as dependencies of application _D_.
And that mess is somehow expected to reduce headache??? Seriously? :(

I'd be glad to continue this discussion if I had more time. Anyway I have no Twitter account so I rest further argumentation.
