### ISSUE TITLE
decode same toml at mac osx & linux os, the result is different

### ISSUE THREAD

**Issue by liujianping** [BurntSushi/toml#77]
title = "subject"
active = "home"

===========
mac osx decode with result:
map[meta:map[title:subject active:home]

linux decode with result:
map[meta:map[title:"subject" active:"home"]

============

so, when i get .meta.active at template, the value is  different  at different os....

**Comment by BurntSushi** [comment]
Please provide enough information for someone else to reproduce. In particular, can you show your code?

**Comment by liujianping** [comment]
you can use the same toml config file，the content like:

title = "subject"
active = "home"

so, when i decode from mac osx, get the 
**map[title:subject active:home]**

but decode from linux, get 
**map[title:"subject" active:"home"]**

from the result , you can find the difference, 

at osx, title is a string, which value is **subject**
but at linux,title is a string, too, but value is **"subject"**, with quotes characters

**Comment by BurntSushi** [comment]
Can you please show your code?

**Comment by liujianping** [comment]
go get github.com/h2object/markdown-pager
go test  @different os, get the string value is different.

**Comment by BurntSushi** [comment]
If you could post a *minimally reproducible* sample of code here in this issue, then that would be great.

**Comment by liujianping** [comment]
with minimal test, it seems the result is right. I'll check my code , thanks for your patience :)
