### ISSUE TITLE
`omitempty` breaks Decode

### ISSUE THREAD

**Issue by chowey** [BurntSushi/toml#89]
With #81, toml supports the `omitempty` tag while encoding a struct. For example:

```go
type S struct {
    V string `toml:"value,omitempty"`
}
```

will skip writing "V" during `toml.Encode()`.

Unfortunately the reverse is not true. `omitempty` has no meaning for `toml.Decode()` and is treated as part of the field name. In the example above, `toml.Decode()` will attempt to decode the field named `value,omitempty` into "V" and will ignore the field named `value`.

**Comment by cespare** [comment]
Fixed by #82.
